"use client";

import Link from "next/link";
import { useEffect, useState, type ReactNode } from "react";
import { ArrowLeft, ArrowRight, CreditCard, PackageCheck, Truck } from "lucide-react";

import TagPreview from "@/components/studio/preview/TagPreview";
import { TAG_DESIGNS } from "@/lib/designs";
import { FINISH_NAME_BY_VALUE } from "@/lib/finishes";
import { TAG_SIZES } from "@/lib/sizes";
import { DELIVERY_NOTICE, DELIVERY_OPTIONS } from "@/lib/checkout/delivery";
import { readOrderDraft, toPreviewConfiguration, updateOrderDraft } from "@/lib/checkout/draft";
import type { CustomerDetails, OrderDraft } from "@/lib/checkout/types";

type CheckoutStage = "review" | "details" | "delivery" | "payment";

const stages: { id: CheckoutStage; label: string }[] = [{ id: "review", label: "Review" }, { id: "details", label: "Details" }, { id: "delivery", label: "Delivery" }, { id: "payment", label: "Payment" }];

function useDraft() {
  const [draft, setDraft] = useState<OrderDraft | null | undefined>(undefined);
  useEffect(() => {
    const frame = window.requestAnimationFrame(() => setDraft(readOrderDraft()));
    return () => window.cancelAnimationFrame(frame);
  }, []);
  function update(next: Parameters<typeof updateOrderDraft>[1]) { if (!draft) return; setDraft(updateOrderDraft(draft, next)); }
  return { draft, update };
}

function Shell({ stage, children }: { stage: CheckoutStage; children: ReactNode }) {
  const active = stages.findIndex((item) => item.id === stage);
  return <main className="min-h-screen bg-[#fbfbfa] py-5 sm:py-8"><div className="mx-auto max-w-6xl px-4 sm:px-6"><header className="flex flex-wrap items-center justify-between gap-5 rounded-[24px] border border-black/[0.06] bg-white px-5 py-4 shadow-sm sm:px-6"><Link href="/" className="inline-flex min-h-10 items-center gap-2 rounded-xl px-2 text-sm font-semibold text-neutral-600 transition hover:bg-neutral-50 hover:text-neutral-950 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-neutral-950"><ArrowLeft className="size-4" />Back to PetTap</Link><ol className="flex items-center gap-2" aria-label="Checkout progress">{stages.map((item, index) => <li key={item.id} aria-current={index === active ? "step" : undefined} className={`hidden rounded-full px-3 py-1.5 text-xs font-semibold sm:block ${index === active ? "bg-neutral-950 text-white" : index < active ? "bg-neutral-100 text-neutral-800" : "text-neutral-400"}`}>{item.label}</li>)}<li className="sm:hidden text-xs font-semibold text-neutral-500">{stages[active].label} of {stages.length}</li></ol></header>{children}</div></main>;
}

function Recovery() { return <Shell stage="review"><section className="mx-auto mt-8 max-w-xl rounded-[28px] border border-black/[0.07] bg-white p-7 text-center shadow-sm sm:p-10"><PackageCheck className="mx-auto size-9 text-neutral-400" /><h1 className="mt-5 text-3xl font-semibold tracking-[-0.05em] text-neutral-950">Your purchase draft is not available.</h1><p className="mt-4 text-sm leading-6 text-neutral-600">Start with PetTap Essential or create a personalised tag in the Studio. Your next selection will create a new review draft.</p><div className="mt-7 flex flex-wrap justify-center gap-3"><Link href="/#tags" className="rounded-2xl bg-neutral-950 px-5 py-3 text-sm font-semibold text-white">Choose Essential</Link><Link href="/studio" className="rounded-2xl border border-black/[0.10] px-5 py-3 text-sm font-semibold text-neutral-900">Open Studio</Link></div></section></Shell>; }

function Summary({ draft }: { draft: OrderDraft }) {
  const configuration = toPreviewConfiguration(draft.purchase);
  const design = TAG_DESIGNS.find((item) => item.id === configuration.design)?.name ?? configuration.design;
  const size = TAG_SIZES.find((item) => item.id === configuration.size)?.title ?? configuration.size;
  const details = draft.purchase.type === "essential" ? [["Shape", design], ["Colour", FINISH_NAME_BY_VALUE[configuration.colour] ?? configuration.colour], ["Size", size], ["Finish", configuration.finish]] : [["Shape", design], ["Colour", FINISH_NAME_BY_VALUE[configuration.colour] ?? configuration.colour], ["Size", size], ["Name", configuration.petName], ["Font", configuration.engravingFont], ["Icon", configuration.engravingIcon === "none" ? "None" : configuration.engravingIcon], ["Material", configuration.material], ["Finish", configuration.finish]];
  return <aside className="rounded-[28px] border border-black/[0.07] bg-white p-5 shadow-[0_16px_44px_rgba(17,17,17,0.05)] sm:p-6"><p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-neutral-400">{draft.purchase.type === "essential" ? "PetTap Essential" : "Your PetTap"}</p><div className="mt-5 flex justify-center rounded-2xl bg-neutral-50 p-5"><div className="w-36"><TagPreview {...configuration} /></div></div><dl className="mt-5 grid grid-cols-2 gap-2.5">{details.map(([label, value]) => <div key={label} className="rounded-xl bg-neutral-50 px-3 py-2.5"><dt className="text-[10px] font-semibold uppercase tracking-[0.12em] text-neutral-400">{label}</dt><dd className="mt-1 truncate text-sm font-medium text-neutral-900">{value}</dd></div>)}</dl><div className="mt-6 flex items-baseline justify-between border-t border-black/[0.06] pt-5"><span className="text-sm font-medium text-neutral-500">Product total</span><span className="text-3xl font-semibold tracking-[-0.05em] text-neutral-950">£{draft.purchase.price.product.toFixed(2)}</span></div></aside>;
}

function Page({ stage, draft, children }: { stage: CheckoutStage; draft: OrderDraft | null | undefined; children: ReactNode }) { if (draft === undefined) return <Shell stage={stage}><div className="mx-auto mt-12 max-w-xl text-center text-sm text-neutral-500" role="status">Loading your purchase draft…</div></Shell>; if (!draft) return <Recovery />; return <Shell stage={stage}><div className="mt-6 grid items-start gap-6 lg:grid-cols-[minmax(0,1fr)_360px]"><section className="rounded-[28px] border border-black/[0.07] bg-white p-6 shadow-[0_16px_44px_rgba(17,17,17,0.04)] sm:p-8">{children}</section><Summary draft={draft} /></div></Shell>; }

export function ReviewCheckout() { const { draft } = useDraft(); return <Page stage="review" draft={draft}>{draft && <><Eyebrow title="Review your PetTap" copy={draft.purchase.type === "essential" ? "A complete NFC tag, ready to activate." : "A made-to-order PetTag, created around your companion."} /><div className="mt-8 rounded-2xl bg-neutral-50 p-5 text-sm leading-6 text-neutral-600"><p className="font-semibold text-neutral-950">Delivery notice</p><p className="mt-2">{DELIVERY_NOTICE}</p></div><div className="mt-8 flex flex-wrap gap-3"><Link href={draft.purchase.type === "essential" ? "/#tags" : "/studio"} className="inline-flex min-h-12 items-center rounded-2xl border border-black/[0.10] px-5 text-sm font-semibold text-neutral-800">Edit {draft.purchase.type === "essential" ? "Essential" : "in Studio"}</Link><Link href="/checkout/details" className="inline-flex min-h-12 items-center gap-2 rounded-2xl bg-neutral-950 px-5 text-sm font-semibold text-white">Continue <ArrowRight className="size-4" /></Link></div></>}</Page>; }

const requiredFields: (keyof CustomerDetails)[] = ["fullName", "email", "phone", "addressLine1", "townOrCity", "postcode", "country"];
const labels: Record<keyof CustomerDetails, string> = { fullName: "Full name", email: "Email", phone: "Phone", addressLine1: "Address line 1", addressLine2: "Address line 2", townOrCity: "Town or city", county: "County", postcode: "Postcode", country: "Country" };

export function DetailsCheckout() { const { draft, update } = useDraft(); const [errors, setErrors] = useState<string[]>([]); function submit() { if (!draft) return; const missing = requiredFields.filter((field) => !draft.customer[field].trim()).map((field) => labels[field]); if (draft.customer.email && !/^\S+@\S+\.\S+$/.test(draft.customer.email)) missing.push("a valid email address"); setErrors(missing); if (!missing.length) window.location.assign("/checkout/delivery"); } return <Page stage="details" draft={draft}>{draft && <><Eyebrow title="Your details" copy="We save this draft only in this browser while payment is being prepared." /><form className="mt-7" noValidate onSubmit={(event) => { event.preventDefault(); submit(); }}>{errors.length > 0 && <div role="alert" className="mb-5 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><p className="font-semibold">Please check the following:</p><ul className="mt-2 list-disc pl-5">{errors.map((error) => <li key={error}>{error}</li>)}</ul></div>}<div className="grid gap-4 sm:grid-cols-2">{(Object.keys(labels) as (keyof CustomerDetails)[]).map((field) => <label key={field} className={field === "addressLine1" || field === "addressLine2" ? "sm:col-span-2" : ""}><span className="text-sm font-medium text-neutral-800">{labels[field]}{requiredFields.includes(field) && <span aria-hidden="true"> *</span>}</span><input required={requiredFields.includes(field)} type={field === "email" ? "email" : field === "phone" ? "tel" : "text"} value={draft.customer[field]} onChange={(event) => update({ customer: { ...draft.customer, [field]: event.target.value } })} className="mt-2 w-full rounded-xl border border-black/[0.10] bg-white px-3.5 py-3 text-base outline-none transition focus:border-black focus:ring-4 focus:ring-black/[0.06]" /></label>)}</div><button type="submit" className="mt-8 flex min-h-13 w-full items-center justify-center gap-2 rounded-2xl bg-neutral-950 px-5 py-3 text-sm font-semibold text-white">Continue to delivery <ArrowRight className="size-4" /></button></form></>}</Page>; }

export function DeliveryCheckout() { const { draft, update } = useDraft(); return <Page stage="delivery" draft={draft}>{draft && <><Eyebrow title="Delivery" copy="Select a provisional delivery preference. Timing and pricing will be confirmed before payment is enabled." /><div className="mt-7 space-y-3">{DELIVERY_OPTIONS.map((option) => <button key={option.id} type="button" onClick={() => update({ deliveryMethod: option.id })} aria-pressed={draft.deliveryMethod === option.id} className={`flex w-full items-start gap-4 rounded-2xl border p-4 text-left transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-neutral-950 ${draft.deliveryMethod === option.id ? "border-neutral-950 bg-neutral-950 text-white" : "border-black/[0.08] hover:border-black/25"}`}><Truck className="mt-0.5 size-5 shrink-0" /><span><span className="block font-semibold">{option.title}</span><span className={`mt-1 block text-sm ${draft.deliveryMethod === option.id ? "text-white/70" : "text-neutral-500"}`}>{option.description}</span><span className={`mt-2 block text-xs ${draft.deliveryMethod === option.id ? "text-white/60" : "text-neutral-400"}`}>{option.priceLabel} · {option.availabilityNote}</span></span></button>)}</div><Link href="/checkout/payment" className={`mt-8 flex min-h-13 items-center justify-center gap-2 rounded-2xl px-5 py-3 text-sm font-semibold ${draft.deliveryMethod ? "bg-neutral-950 text-white" : "pointer-events-none bg-neutral-100 text-neutral-400"}`}>Continue to payment <ArrowRight className="size-4" /></Link></>}</Page>; }

export function PaymentCheckout() { const { draft } = useDraft(); return <Page stage="payment" draft={draft}>{draft && <><Eyebrow title="Payment preparation" copy="Payment is not enabled in this preview. PetTap does not collect or store card details here." /><div className="mt-8 rounded-2xl border border-black/[0.06] bg-neutral-50 p-6"><CreditCard className="size-6 text-neutral-700" /><h2 className="mt-4 text-xl font-semibold tracking-[-0.03em] text-neutral-950">A secure provider will be connected here.</h2><p className="mt-3 text-sm leading-6 text-neutral-600">The checkout model is ready for a provider such as Stripe, Apple Pay or PayPal. Payment-session creation remains isolated behind a provider-agnostic service and is intentionally unavailable until configured.</p></div><Link href="/checkout/delivery" className="mt-8 inline-flex min-h-12 items-center gap-2 rounded-2xl border border-black/[0.10] px-5 text-sm font-semibold text-neutral-800">Back to delivery</Link></>}</Page>; }

function Eyebrow({ title, copy }: { title: string; copy: string }) { return <div><p className="text-[11px] font-semibold uppercase tracking-[0.22em] text-neutral-400">PetTap checkout</p><h1 className="mt-3 text-3xl font-semibold tracking-[-0.045em] text-neutral-950 sm:text-4xl">{title}</h1><p className="mt-3 max-w-xl text-sm leading-6 text-neutral-600">{copy}</p></div>; }
