import { CalendarDays, PawPrint, ShieldCheck, Tag } from "lucide-react";

import Card from "@/components/ui/Card";
import type { ActivationContent, ActivationPet, TagInformation } from "@/lib/activation";

export default function ActivationSummary({ tag, pet, content, onActivate }: { tag: TagInformation; pet: ActivationPet; content: ActivationContent["confirmation"]; onActivate: () => void }) {
  const details = [{ label: content.labels.tagId, value: tag.id, icon: Tag }, { label: content.labels.petName, value: pet.name, icon: PawPrint }, { label: content.labels.protection, value: "Ready to protect", icon: ShieldCheck }, { label: content.labels.activationDate, value: "Today", icon: CalendarDays }];
  return <section aria-labelledby="activation-summary" className="mx-auto max-w-2xl"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-sky-700">Step 3 of 3</p><h1 id="activation-summary" className="mt-2 text-3xl font-semibold tracking-tight text-foreground sm:text-4xl">{content.title}</h1><p className="mt-3 leading-7 text-muted-foreground">{content.description}</p><Card className="mt-8 overflow-hidden"><div className="bg-gradient-to-r from-[#111111] to-[#263752] p-6 text-white"><p className="text-sm font-medium text-white/65">PetTap</p><p className="mt-2 text-2xl font-semibold">{pet.name} is almost protected.</p></div><dl className="grid gap-px bg-neutral-100 sm:grid-cols-2">{details.map(({ label, value, icon: Icon }) => <div key={label} className="bg-white p-5"><Icon className="h-5 w-5 text-sky-700" strokeWidth={1.8} /><dt className="mt-4 text-sm font-medium text-muted-foreground">{label}</dt><dd className="mt-1 font-semibold text-foreground">{value}</dd></div>)}</dl></Card><button type="button" onClick={onActivate} className="mt-6 flex min-h-14 w-full items-center justify-center rounded-2xl bg-[#111111] px-6 text-base font-semibold text-white shadow-[0_12px_28px_rgba(0,0,0,.14)] transition-all hover:-translate-y-0.5 hover:bg-black focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-sky-600">{content.action}</button></section>;
}
