import { useState } from "react";
import { CheckCircle2, KeyRound } from "lucide-react";

import { ACTIVATION_CODE_PATTERN, type ActivationContent } from "@/lib/activation";

export default function ManualCodeForm({ content, onDetected }: { content: ActivationContent["methods"]["manual"]; onDetected: () => void }) {
  const [code, setCode] = useState("");
  const [error, setError] = useState("");
  const submit = () => { if (ACTIVATION_CODE_PATTERN.test(code.trim().toUpperCase())) { onDetected(); return; } setError("That code does not look quite right. You can still continue in demo mode."); };
  return <section aria-labelledby="activation-code-heading" className="mx-auto max-w-xl py-6 sm:py-12"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-sky-50 text-sky-700"><KeyRound className="h-7 w-7" /></div><p className="mt-7 text-sm font-semibold uppercase tracking-[0.16em] text-sky-700">Step 1 of 3</p><h1 id="activation-code-heading" className="mt-2 text-3xl font-semibold tracking-tight text-foreground sm:text-4xl">{content.title}</h1><p className="mt-3 leading-7 text-muted-foreground">{content.detail}</p><label htmlFor="activation-code" className="mt-8 block text-sm font-semibold text-foreground">Activation code</label><input id="activation-code" value={code} onChange={(event) => { setCode(event.target.value.toUpperCase()); setError(""); }} placeholder={content.placeholder} className="mt-2 min-h-14 w-full rounded-2xl border border-neutral-300 bg-white px-4 font-mono text-base tracking-[0.08em] text-foreground shadow-sm outline-none transition focus:border-sky-600 focus:ring-4 focus:ring-sky-100" aria-describedby={error ? "activation-code-error" : undefined} />{error && <p id="activation-code-error" role="alert" className="mt-3 text-sm font-medium text-rose-700">{error}</p>}<button type="button" onClick={submit} className="mt-5 min-h-14 w-full rounded-2xl bg-[#111111] px-6 font-semibold text-white shadow-[0_12px_28px_rgba(0,0,0,.14)] transition-all hover:-translate-y-0.5 hover:bg-black focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-sky-600">{content.action}</button>{error && <button type="button" onClick={onDetected} className="mt-3 inline-flex min-h-12 items-center gap-2 px-3 text-sm font-semibold text-sky-700 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-sky-600"><CheckCircle2 className="h-4 w-4" />{content.demoAction}</button>}</section>;
}
