import { describe, expect, it } from "vitest";
import { addOrderNoteSchema, changeOrderStatusSchema, createFulfilmentSchema } from "@/features/admin/orders/schemas/admin-order-actions";
import { assertAdminOrderTransition, assertFulfilmentTransition, formatAdminMoney, formatFulfilmentStatus, parseAdminPersonalisation } from "@/features/admin/orders/services/admin-order-domain";
import { shipOrderSchema, updateFulfilmentStatusSchema, updateProductionStatusSchema } from "@/features/admin/orders/schemas/admin-order-actions";

const id = "11111111-1111-4111-8111-111111111111";
describe("admin order domain", () => {
  it("allows only existing commerce lifecycle transitions", () => { expect(() => assertAdminOrderTransition("paid", "in_production")).not.toThrow(); expect(() => assertAdminOrderTransition("completed", "paid")).toThrow(); });
  it("requires explicit confirmation for critical changes", () => { expect(changeOrderStatusSchema.safeParse({ orderId: id, nextStatus: "cancelled", confirmation: "CHANGE STATUS" }).success).toBe(true); expect(changeOrderStatusSchema.safeParse({ orderId: id, nextStatus: "cancelled", confirmation: "cancel" }).success).toBe(false); expect(createFulfilmentSchema.safeParse({ orderId: id, confirmation: "CREATE FULFILMENT" }).success).toBe(true); });
  it("validates notes, money and flexible personalisation", () => { expect(addOrderNoteSchema.safeParse({ orderId: id, body: "Production note" }).success).toBe(true); expect(addOrderNoteSchema.safeParse({ orderId: id, body: "" }).success).toBe(false); expect(formatAdminMoney(1299, "GBP")).toContain("12.99"); expect(parseAdminPersonalisation({ petName: "Milo", shape: "round" })?.petName).toBe("Milo"); expect(parseAdminPersonalisation({ unknown: "value" })).toBeNull(); });
  it("keeps payment and fulfilment lifecycles separate", () => { expect(() => assertFulfilmentTransition("unfulfilled", "in_production")).not.toThrow(); expect(() => assertFulfilmentTransition("in_production", "shipped")).toThrow(); expect(() => assertFulfilmentTransition("shipped", "cancelled")).toThrow(); expect(formatFulfilmentStatus("ready")).toBe("Printed"); expect(updateFulfilmentStatusSchema.safeParse({ orderId: id, nextStatus: "ready", confirmation: "UPDATE FULFILMENT" }).success).toBe(true); });
  it("validates production and shipping actions without accepting arbitrary payloads", () => { expect(updateProductionStatusSchema.safeParse({ orderId: id, nextStatus: "printing", confirmation: "UPDATE PRODUCTION" }).success).toBe(true); expect(updateProductionStatusSchema.safeParse({ orderId: id, nextStatus: "shipped", confirmation: "UPDATE PRODUCTION" }).success).toBe(false); expect(shipOrderSchema.safeParse({ orderId: id, trackingNumber: "RM123456789GB", confirmation: "MARK SHIPPED" }).success).toBe(true); expect(shipOrderSchema.safeParse({ orderId: id, trackingNumber: "", confirmation: "MARK SHIPPED" }).success).toBe(false); });
});
