import Image from "next/image";
import Link from "next/link";
import { ArrowLeft, CheckCircle2, Tag } from "lucide-react";

import type { PetWorkspace } from "@/lib/dashboard";

export default function WorkspaceHeader({ pet }: { pet: PetWorkspace }) {
  return <header className="border-b border-neutral-200/80 bg-white/85 backdrop-blur-xl"><div className="mx-auto max-w-6xl px-5 py-5 sm:px-8 sm:py-7"><Link href="/dashboard" className="inline-flex min-h-10 items-center gap-2 rounded-xl px-2 text-sm font-semibold text-muted-foreground transition-colors hover:bg-neutral-100 hover:text-foreground focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-sky-600"><ArrowLeft className="h-4 w-4" />Back to dashboard</Link><div className="mt-5 flex items-end justify-between gap-4"><div className="flex min-w-0 items-center gap-4"><div className="relative h-20 w-20 shrink-0 overflow-hidden rounded-3xl bg-neutral-100 shadow-sm sm:h-24 sm:w-24"><Image src={pet.photo} alt={pet.name} fill sizes="96px" className="object-cover" /></div><div className="min-w-0"><p className="text-sm font-medium text-muted-foreground">Pet workspace</p><h1 className="truncate text-3xl font-semibold tracking-tight text-foreground sm:text-4xl">{pet.name}</h1><p className="mt-1 text-sm text-muted-foreground sm:text-base">{pet.breed} · {pet.age}</p></div></div><div className="hidden text-right sm:block"><span className="inline-flex items-center gap-1.5 rounded-full bg-emerald-50 px-3 py-1.5 text-sm font-semibold text-emerald-800"><CheckCircle2 className="h-4 w-4" />Protected</span><p className="mt-2 inline-flex items-center gap-1.5 text-sm text-muted-foreground"><Tag className="h-4 w-4" />{pet.tagId}</p></div></div><div className="mt-5 flex flex-wrap gap-2 sm:hidden"><span className="inline-flex items-center gap-1.5 rounded-full bg-emerald-50 px-3 py-1.5 text-sm font-semibold text-emerald-800"><CheckCircle2 className="h-4 w-4" />Protected</span><span className="inline-flex items-center gap-1.5 rounded-full bg-neutral-100 px-3 py-1.5 text-sm font-medium text-muted-foreground"><Tag className="h-4 w-4" />{pet.tagId}</span></div></div></header>;
}
