import { notFound } from "next/navigation";

import { parseAdminPersonalisation } from "@/features/admin/orders/services/admin-order-domain";
import { AdminOrderNotFoundError, AdminOrderService } from "@/features/admin/orders/services/admin-order-service";

export default async function ProductionSheetPage({ params }: { params: Promise<{ orderId: string }> }) {
  const { orderId } = await params;
  let detail;
  try { detail = await new AdminOrderService().detail(orderId); } catch (error) { if (error instanceof AdminOrderNotFoundError) notFound(); throw error; }
  return <main className="mx-auto max-w-[210mm] bg-white p-8 text-black print:p-0"><style>{`@media print { body { background: white; } main { max-width: none; } }`}</style><header className="border-b-2 border-black pb-6"><p className="text-sm font-bold tracking-[.25em]">PETTAP</p><h1 className="mt-3 text-3xl font-bold">Production Sheet</h1><dl className="mt-5 grid grid-cols-2 gap-4 text-sm"><div><dt className="text-neutral-600">Order number</dt><dd className="font-semibold">{detail.order.orderNumber}</dd></div><div><dt className="text-neutral-600">Order date</dt><dd className="font-semibold">{new Intl.DateTimeFormat("en-GB", { dateStyle: "medium" }).format(detail.order.createdAt)}</dd></div></dl></header><section className="mt-8 space-y-6">{detail.items.map((item) => { const p = parseAdminPersonalisation(item.personalisation); return <article className="border-b border-black pb-6" key={item.id}><h2 className="text-lg font-bold">{item.productName}</h2><dl className="mt-4 grid grid-cols-2 gap-x-8 gap-y-3 text-sm"><div><dt className="text-neutral-600">SKU</dt><dd>{item.sku}</dd></div><div><dt className="text-neutral-600">Quantity</dt><dd>{item.quantity}</dd></div><div><dt className="text-neutral-600">Pet name</dt><dd>{p?.petName ?? "—"}</dd></div><div><dt className="text-neutral-600">Collection</dt><dd>{p?.collection ?? "—"}</dd></div><div><dt className="text-neutral-600">Shape / colour</dt><dd>{p?.shape ?? "—"} / {p?.colour ?? "—"}</dd></div><div><dt className="text-neutral-600">Size / finish</dt><dd>{p?.size ?? "—"} / {p?.finish ?? "—"}</dd></div></dl></article>; })}</section><section className="mt-8 grid gap-6 text-sm"><p>NFC UID: ______________________________________________</p><p>Tag URL: ______________________________________________</p><p>Operator: _____________________________________________</p><p>Print started: _________________________________________</p><p>Quality checked: _______________________________________</p><p>Notes: _________________________________________________</p></section></main>;
}
