import "server-only";
import { auditLogs } from "@/db/schema";
import { createDatabaseClient } from "@/lib/backend/db";
import { PublicPetPhotoService } from "@/features/pets/services/public-pet-photo-service";
import { PublicTagRepository } from "@/features/nfc/repositories/public-tag-repository";
import { allowPublicTagRequest } from "./public-tag-rate-limit";
export type PublicLostPetDto={name?:string;species?:string;photoUrl?:string;reportedAt?:string};
export type PublicTagResolution={state:"not_found"|"not_activated"|"suspended"|"retired"|"unavailable"|"rate_limited"}|{state:"active";profile:{name?:string;species:string;photoUrl?:string}}|{state:"lost";profile:PublicLostPetDto};
export type PublicTagAuditEvent={state:PublicTagResolution["state"];tagId:string|null};
export interface PublicTagAuditWriter{write(event:PublicTagAuditEvent):Promise<void>}
export class DatabasePublicTagAuditWriter implements PublicTagAuditWriter{async write(event:PublicTagAuditEvent){await createDatabaseClient().insert(auditLogs).values({action:`public.tag.${event.state}`,targetType:"nfc_tag",targetId:event.tagId,result:"success",metadata:{state:event.state}})}}
export class PublicTagResolverService {constructor(private readonly repository=new PublicTagRepository(),private readonly photos=new PublicPetPhotoService(),private readonly audit:PublicTagAuditWriter=new DatabasePublicTagAuditWriter(),private readonly rateLimit=allowPublicTagRequest){}async resolveByPublicCode(input:{publicCode:string;ip:string}):Promise<PublicTagResolution>{if(!/^[A-Za-z0-9_-]{3,128}$/.test(input.publicCode)||!this.rateLimit(input.ip))return {state:"rate_limited"};const tag=await this.repository.findByPublicCode(input.publicCode);let result:PublicTagResolution;if(!tag)result={state:"not_found"};else if(tag.status==="unassigned")result={state:"not_activated"};else if(tag.status==="suspended")result={state:"suspended"};else if(tag.status==="retired")result={state:"retired"};else if(!tag.pet||!tag.petId||tag.pet.archivedAt||tag.accountId!==tag.pet.accountId||tag.activationCount!==1)result={state:"unavailable"};else if(tag.status==="lost"){const report=tag.lostReport;if(!report||report.status!=="open"||report.petId!==tag.pet.id||report.tagId!==tag.tagId)result={state:"unavailable"};else if(!tag.pet.publicProfileEnabled||!tag.preferences)result={state:"lost",profile:{}};else {const photoUrl=tag.preferences.showPhoto?await this.photos.sign(tag.photoPath):null;result={state:"lost",profile:{...(tag.preferences.showName?{name:tag.pet.name}:{}),...(tag.preferences.showBreed?{species:tag.pet.species}:{}),...(photoUrl?{photoUrl}:{}),reportedAt:report.openedAt.toISOString().slice(0,10)}}}}else if(tag.status!=="active"||!tag.pet.publicProfileEnabled||!tag.preferences)result={state:"unavailable"};else {const photoUrl=tag.preferences.showPhoto?await this.photos.sign(tag.photoPath):null;result={state:"active",profile:{species:tag.pet.species,...(tag.preferences.showName?{name:tag.pet.name}:{}),...(photoUrl?{photoUrl}:{})}}}try{await this.audit.write({state:result.state,tagId:tag?.tagId??null})}catch{/* best-effort audit: public response stays safe */}return result;}}
