/* eslint-disable @next/next/no-img-element -- signed private Storage URLs are intentionally short-lived. */
import Link from "next/link";
import { notFound } from "next/navigation";
import Card from "@/components/ui/Card";
import { CustomerPetManagementService } from "@/features/account/services/customer-pet-management-service";
import { CustomerPetForm } from "@/features/account/components/customer-pet-form";
import { DeletePetButton } from "@/features/account/components/delete-customer-pet-button";
import { CustomerPetTagLinkCard } from "@/features/account/components/customer-pet-tag-link-card";
import { CustomerPetTagActivationService } from "@/features/account/services/customer-pet-tag-activation-service";
import { CustomerPetTagLinkService } from "@/features/account/services/customer-pet-tag-link-service";
import { CustomerPetPublicProfileCard } from "@/features/account/components/customer-pet-public-profile-card";
import { CustomerPetPublicProfileService } from "@/features/account/services/customer-pet-public-profile-service";
import { DrizzleCustomerPetFoundationRepository } from "@/features/account/repositories/customer-pet-foundation-repository";
import { getAuthenticatedAccountId } from "@/features/commerce/services/commerce-account-service";
import { LostModeService } from "@/features/lost-mode/services/lost-mode-service";
import { LostModeOwnerPanel } from "@/features/lost-mode/components/lost-mode-owner-panel";
export default async function ManagePetPage({params}:{params:Promise<{publicIdentifier:string}>}){const {publicIdentifier}=await params;const pet=await new CustomerPetManagementService().get(publicIdentifier);if(!pet)notFound();const tagLink=await new CustomerPetTagLinkService().getLink(publicIdentifier);const tagActivation=await new CustomerPetTagActivationService().getActivation(publicIdentifier);const profile=await new CustomerPetPublicProfileService().get(publicIdentifier);const foundation=await new DrizzleCustomerPetFoundationRepository().findOwnedPetByPublicIdentifier(await getAuthenticatedAccountId(),publicIdentifier);const lostStatus=foundation?await new LostModeService().getStatus(foundation.id):null;const publicProfile=profile??{enabled:false,showPhoto:false,showName:false,showBreed:false,showAge:false,publicMessage:null,updatedAt:null};return <section><Link href="/account/pets" className="text-sm font-semibold underline underline-offset-4">Back to pets</Link><div className="mt-5 flex items-center gap-4">{pet.photoUrl?<img src={pet.photoUrl} alt="" className="size-20 rounded-3xl object-cover"/>:null}<div><p className="text-xs font-semibold uppercase tracking-[.18em] text-neutral-500">Private profile</p><h1 className="mt-1 text-4xl font-semibold tracking-[-.06em]">{pet.name}</h1></div></div><Card variant="surface" className="mt-8 p-6 sm:p-8"><h2 className="text-xl font-semibold">Pet details</h2><CustomerPetForm pet={pet}/></Card><Card variant="outlined" className="mt-6 p-6"><h2 className="text-xl font-semibold">NFC Tag</h2><div className="mt-4"><CustomerPetTagLinkCard petPublicIdentifier={pet.publicIdentifier} link={tagLink} activation={tagActivation}/></div></Card><Card variant="outlined" className="mt-6 p-6"><h2 className="text-xl font-semibold">Public Profile</h2><p className="mt-1 text-sm text-neutral-600">Control exactly what a person sees after tapping your active PetTap.</p><CustomerPetPublicProfileCard petPublicIdentifier={pet.publicIdentifier} profile={publicProfile}/></Card>{foundation?<div className="mt-6"><LostModeOwnerPanel petId={foundation.id} status={lostStatus}/></div>:null}<Card variant="outlined" className="mt-6 p-6"><h2 className="font-semibold text-rose-800">Delete this pet</h2><p className="mt-1 text-sm text-neutral-600">This only works while the profile has no linked records.</p><DeletePetButton publicIdentifier={pet.publicIdentifier}/></Card></section>}
