/* eslint-disable @next/next/no-img-element -- signed private Storage URLs are intentionally short-lived. */
import Link from "next/link";
import { notFound } from "next/navigation";
import Card from "@/components/ui/Card";
import { CustomerPetManagementService } from "@/features/account/services/customer-pet-management-service";
import { CustomerPetForm } from "@/features/account/components/customer-pet-form";
import { DeletePetButton } from "@/features/account/components/delete-customer-pet-button";
import { CustomerPetTagLinkCard } from "@/features/account/components/customer-pet-tag-link-card";
import { CustomerPetTagLinkService } from "@/features/account/services/customer-pet-tag-link-service";
export default async function ManagePetPage({params}:{params:Promise<{publicIdentifier:string}>}){const {publicIdentifier}=await params;const pet=await new CustomerPetManagementService().get(publicIdentifier);if(!pet)notFound();const tagLink=await new CustomerPetTagLinkService().getLink(publicIdentifier);return <section><Link href="/account/pets" className="text-sm font-semibold underline underline-offset-4">Back to pets</Link><div className="mt-5 flex items-center gap-4">{pet.photoUrl?<img src={pet.photoUrl} alt="" className="size-20 rounded-3xl object-cover"/>:null}<div><p className="text-xs font-semibold uppercase tracking-[.18em] text-neutral-500">Private profile</p><h1 className="mt-1 text-4xl font-semibold tracking-[-.06em]">{pet.name}</h1></div></div><Card variant="surface" className="mt-8 p-6 sm:p-8"><h2 className="text-xl font-semibold">Pet details</h2><CustomerPetForm pet={pet}/></Card><Card variant="outlined" className="mt-6 p-6"><h2 className="text-xl font-semibold">NFC Tag</h2><div className="mt-4"><CustomerPetTagLinkCard petPublicIdentifier={pet.publicIdentifier} link={tagLink}/></div></Card><Card variant="outlined" className="mt-6 p-6"><h2 className="font-semibold text-rose-800">Delete this pet</h2><p className="mt-1 text-sm text-neutral-600">This only works while the profile has no linked records.</p><DeletePetButton publicIdentifier={pet.publicIdentifier}/></Card></section>}
