import "server-only";
import { and, count, desc, eq } from "drizzle-orm";
import { auditLogs, contactRequests, lostReports, pets } from "@/db/schema";
import { createDatabaseClient } from "@/lib/backend/db";

export type ContactRequestAudit={action:"contact.request.created"|"contact.request.denied"|"contact.request.invalid"|"contact.request.duplicate";tagId:string|null;lostReportId:string|null;result:"success"|"denied";reason:string};
export type NewContactRequest={lostReportId:string;petId:string;tagId:string;finderName:string;finderContact:string;message:string;actorHash:string;finderConsentAcceptedAt:Date};
export type ContactRequestRecord={id:string;lostReportId:string;petId:string;tagId:string;status:"pending"|"delivered"|"closed"|"expired"|"cancelled";createdAt:Date};
export type ContactRequestCreateResult={record:ContactRequestRecord;created:boolean};
export type OwnerContactRequestRecord=ContactRequestRecord & {finderName:string;finderContact:string;message:string;petDisplayName:string;processedAt:Date|null;resolvedAt:Date|null};
export type OwnerContactRequestPage={rows:OwnerContactRequestRecord[];page:number;pageSize:number;total:number};
export type ContactRequestTransition={outcome:"updated"|"idempotent"|"not_found"|"invalid_transition";previousStatus:"pending"|"delivered"|"closed"|"expired"|"cancelled"|null;record:OwnerContactRequestRecord|null};
export type ContactRequestLifecycleAudit={action:"contact.request.viewed"|"contact.request.delivered"|"contact.request.closed"|"contact.request.expired";contactRequestId:string;petId:string;accountId:string;previousStatus:"pending"|"delivered"|"closed"|"expired"|"cancelled"|null;nextStatus:"delivered"|"closed"|"expired"|null;result:"success"};

export interface ContactRequestRepository { createContactRequest(input:NewContactRequest):Promise<ContactRequestCreateResult>; findPending(accountId:string):Promise<ContactRequestRecord[]>; markDelivered(accountId:string,id:string):Promise<boolean>; close(accountId:string,id:string):Promise<boolean>; expire(id:string):Promise<boolean>; recordAudit(event:ContactRequestAudit):Promise<void>; }
export interface OwnerContactRequestRepository { listForOwner(accountId:string,pagination:{page:number;pageSize:number}):Promise<OwnerContactRequestPage>; countPendingForOwner(accountId:string):Promise<number>; getInboxSummary(accountId:string):Promise<{pendingCount:number}>; findOwnedById(accountId:string,id:string):Promise<OwnerContactRequestRecord|null>; transitionOwned(accountId:string,id:string,nextStatus:"delivered"|"closed"|"expired"):Promise<ContactRequestTransition>; recordLifecycleAudit(event:ContactRequestLifecycleAudit):Promise<void>; }

const ownerColumns={id:contactRequests.id,lostReportId:contactRequests.lostReportId,petId:contactRequests.petId,tagId:contactRequests.tagId,status:contactRequests.status,createdAt:contactRequests.createdAt,finderName:contactRequests.finderName,finderContact:contactRequests.finderContact,message:contactRequests.message,petDisplayName:pets.name,processedAt:contactRequests.processedAt,resolvedAt:contactRequests.resolvedAt};
const asStatus=(value:string):ContactRequestRecord["status"]=>value as ContactRequestRecord["status"];

export class DrizzleContactRequestRepository implements ContactRequestRepository, OwnerContactRequestRepository {
  async createContactRequest(input:NewContactRequest):Promise<ContactRequestCreateResult>{const db=createDatabaseClient();return db.transaction(async(tx)=>{const[record]=await tx.insert(contactRequests).values({...input}).onConflictDoNothing({target:[contactRequests.lostReportId,contactRequests.actorHash]}).returning({id:contactRequests.id,lostReportId:contactRequests.lostReportId,petId:contactRequests.petId,tagId:contactRequests.tagId,status:contactRequests.status,createdAt:contactRequests.createdAt});if(record){await tx.insert(auditLogs).values({action:"contact.request.created",targetType:"contact_request",targetId:record.id,result:"success",metadata:{tagId:input.tagId,lostReportId:input.lostReportId}});return{record:record as ContactRequestRecord,created:true}}const[existing]=await tx.select({id:contactRequests.id,lostReportId:contactRequests.lostReportId,petId:contactRequests.petId,tagId:contactRequests.tagId,status:contactRequests.status,createdAt:contactRequests.createdAt}).from(contactRequests).where(and(eq(contactRequests.lostReportId,input.lostReportId),eq(contactRequests.actorHash,input.actorHash))).limit(1);if(!existing)throw new Error("Contact request idempotency lookup failed.");return{record:existing as ContactRequestRecord,created:false}})}
  async findPending(accountId:string){const db=createDatabaseClient();return db.select({id:contactRequests.id,lostReportId:contactRequests.lostReportId,petId:contactRequests.petId,tagId:contactRequests.tagId,status:contactRequests.status,createdAt:contactRequests.createdAt}).from(contactRequests).innerJoin(lostReports,eq(lostReports.id,contactRequests.lostReportId)).innerJoin(pets,eq(pets.id,lostReports.petId)).where(and(eq(pets.accountId,accountId),eq(contactRequests.status,"pending"))).orderBy(desc(contactRequests.createdAt)) as Promise<ContactRequestRecord[]>}
  async markDelivered(accountId:string,id:string){return this.updateOwned(accountId,id,"delivered",{processedAt:new Date()})}
  async close(accountId:string,id:string){return this.updateOwned(accountId,id,"closed",{resolvedAt:new Date()})}
  async expire(id:string){const db=createDatabaseClient();const rows=await db.update(contactRequests).set({status:"expired",updatedAt:new Date()}).where(and(eq(contactRequests.id,id),eq(contactRequests.status,"pending"))).returning({id:contactRequests.id});return rows.length===1}
  async recordAudit(event:ContactRequestAudit){const db=createDatabaseClient();await db.insert(auditLogs).values({action:event.action,targetType:"contact_request",targetId:null,result:event.result,metadata:{tagId:event.tagId,lostReportId:event.lostReportId,reason:event.reason}})}
  async listForOwner(accountId:string,{page,pageSize}:{page:number;pageSize:number}){const db=createDatabaseClient();const offset=(page-1)*pageSize;const scope=eq(pets.accountId,accountId);const [rows,totalRows]=await Promise.all([db.select(ownerColumns).from(contactRequests).innerJoin(lostReports,eq(lostReports.id,contactRequests.lostReportId)).innerJoin(pets,eq(pets.id,contactRequests.petId)).where(scope).orderBy(desc(contactRequests.createdAt)).limit(pageSize).offset(offset),db.select({value:count()}).from(contactRequests).innerJoin(lostReports,eq(lostReports.id,contactRequests.lostReportId)).innerJoin(pets,eq(pets.id,contactRequests.petId)).where(scope)]);return{rows:rows.map((row)=>({...row,status:asStatus(row.status)}) as OwnerContactRequestRecord),page,pageSize,total:Number(totalRows[0]?.value??0)}}
  async countPendingForOwner(accountId:string){const db=createDatabaseClient();const rows=await db.select({value:count()}).from(contactRequests).innerJoin(lostReports,eq(lostReports.id,contactRequests.lostReportId)).innerJoin(pets,eq(pets.id,contactRequests.petId)).where(and(eq(pets.accountId,accountId),eq(contactRequests.status,"pending")));return Number(rows[0]?.value??0)}
  async getInboxSummary(accountId:string){return{pendingCount:await this.countPendingForOwner(accountId)}}
  async findOwnedById(accountId:string,id:string){const db=createDatabaseClient();const [row]=await db.select(ownerColumns).from(contactRequests).innerJoin(lostReports,eq(lostReports.id,contactRequests.lostReportId)).innerJoin(pets,eq(pets.id,contactRequests.petId)).where(and(eq(contactRequests.id,id),eq(pets.accountId,accountId))).limit(1);return row?{...row,status:asStatus(row.status)} as OwnerContactRequestRecord:null}
  async transitionOwned(accountId:string,id:string,nextStatus:"delivered"|"closed"|"expired"):Promise<ContactRequestTransition>{const db=createDatabaseClient();return db.transaction(async(tx)=>{const [record]=await tx.select(ownerColumns).from(contactRequests).innerJoin(lostReports,eq(lostReports.id,contactRequests.lostReportId)).innerJoin(pets,eq(pets.id,contactRequests.petId)).where(and(eq(contactRequests.id,id),eq(pets.accountId,accountId))).limit(1);if(!record)return{outcome:"not_found",previousStatus:null,record:null};const owned={...record,status:asStatus(record.status)} as OwnerContactRequestRecord;if(owned.status===nextStatus)return{outcome:"idempotent",previousStatus:owned.status,record:owned};const allowed=(owned.status==="pending"&&["delivered","closed","expired"].includes(nextStatus))||(owned.status==="delivered"&&["closed","expired"].includes(nextStatus));if(!allowed)return{outcome:"invalid_transition",previousStatus:owned.status,record:owned};const now=new Date();const timestamps=nextStatus==="delivered"?{processedAt:now}:{resolvedAt:now};const [updated]=await tx.update(contactRequests).set({status:nextStatus,updatedAt:now,...timestamps}).where(and(eq(contactRequests.id,id),eq(contactRequests.status,owned.status))).returning({id:contactRequests.id});if(!updated)return{outcome:"not_found",previousStatus:owned.status,record:null};return{outcome:"updated",previousStatus:owned.status,record:{...owned,status:nextStatus,...timestamps}}})}
  async recordLifecycleAudit(event:ContactRequestLifecycleAudit){const db=createDatabaseClient();await db.insert(auditLogs).values({accountId:event.accountId,action:event.action,targetType:"contact_request",targetId:event.contactRequestId,result:event.result,metadata:{petId:event.petId,previousStatus:event.previousStatus,nextStatus:event.nextStatus}})}
  private async updateOwned(accountId:string,id:string,status:"delivered"|"closed",timestamps:Record<string,Date>){const db=createDatabaseClient();return db.transaction(async(tx)=>{const[owned]=await tx.select({id:contactRequests.id}).from(contactRequests).innerJoin(lostReports,eq(lostReports.id,contactRequests.lostReportId)).innerJoin(pets,eq(pets.id,lostReports.petId)).where(and(eq(contactRequests.id,id),eq(pets.accountId,accountId),eq(contactRequests.status,"pending"))).limit(1);if(!owned)return false;const rows=await tx.update(contactRequests).set({status,updatedAt:new Date(),...timestamps}).where(and(eq(contactRequests.id,id),eq(contactRequests.status,"pending"))).returning({id:contactRequests.id});return rows.length===1})}
}
