"use client";

import Image from "next/image";
import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import { Camera, Check, ChevronLeft, ChevronRight, ImagePlus, LockKeyhole, PawPrint, ShieldCheck, Sparkles } from "lucide-react";
import { useMemo, useRef, useState } from "react";

import { Button } from "@/components/ui/button";
import Card from "@/components/ui/Card";
import { abandonEventDemoSession, completeEventDemoProfile, getEventDemoPreview, startEventDemoSession, updateEventDemoContactAndPrivacy, updateEventDemoPetDetails, uploadEventDemoPhoto } from "@/features/event-demo/actions/event-demo-actions";

type Stage = "welcome" | "pet" | "photo" | "privacy" | "preview" | "success";
type Session = {
  petName: string | null; species: "dog" | "cat" | "other" | null; breed: string | null; age: string | null; personality: string | null; ownerFirstName: string | null;
  contactTelephone?: string | null; contactEmail?: string | null;
  showOwnerFirstName: boolean; showTelephone: boolean; showEmail: boolean; showBreed: boolean; showAge: boolean; showPersonality: boolean;
};
type PrivacyFormValue = { contactTelephone: string | null; contactEmail: string | null; visibility: Pick<Session, "showOwnerFirstName" | "showTelephone" | "showEmail" | "showBreed" | "showAge" | "showPersonality">; demoConsentAccepted: boolean; marketingConsent: boolean };
type ActionResult = { status: "success" | "error"; message: string; step?: Stage; previewUrl?: string | null; sessionPublicId?: string };

const steps: Array<{ id: Exclude<Stage, "welcome" | "success">; label: string; description: string }> = [
  { id: "pet", label: "Pet", description: "Tell us about your pet" },
  { id: "photo", label: "Photo", description: "Add a clear photo" },
  { id: "privacy", label: "Privacy", description: "Choose what to share" },
  { id: "preview", label: "Review", description: "Check your profile" },
];
const MAX_EVENT_DEMO_PHOTO_SIZE = 6 * 1024 * 1024;
const eventDemoPhotoTypes = new Set(["image/jpeg", "image/png", "image/webp", "image/heic", "image/heif"]);
const transition = { duration: 0.2, ease: "easeOut" } as const;

export function EventDemoExperience({ publicCode, restoredSession }: { publicCode: string; restoredSession: Session | null }) {
  const [stage, setStage] = useState<Stage>(restoredSession ? "pet" : "welcome");
  const [session, setSession] = useState<Session | null>(restoredSession);
  const [message, setMessage] = useState<string | null>(restoredSession ? "Your saved demo has been restored." : null);
  const [error, setError] = useState<string | null>(null);
  const [pending, setPending] = useState(false);
  const [previewUrl, setPreviewUrl] = useState<string | null>(null);
  const [profilePublicId, setProfilePublicId] = useState<string | null>(null);
  const reduceMotion = useReducedMotion();
  const stageIndex = useMemo(() => steps.findIndex((item) => item.id === stage), [stage]);

  async function invoke(action: () => Promise<ActionResult>) {
    setPending(true); setError(null); setMessage(null);
    try {
      const result = await action();
      if (result.status === "error") { setError(result.message); return; }
      setMessage(result.message);
      if (result.previewUrl) setPreviewUrl(result.previewUrl);
      if (result.sessionPublicId) setProfilePublicId(result.sessionPublicId);
      if (result.step) setStage(result.step);
    } catch {
      setError("We couldn't complete that right now. Please check your connection and try again.");
    } finally {
      setPending(false);
    }
  }

  const shell = (content: React.ReactNode) => <main className="min-h-screen bg-[#f7f8fa] px-4 py-5 text-[#07152e] sm:px-6 sm:py-10"><div className="mx-auto max-w-3xl"><ActivationHeader />{stage !== "welcome" && stage !== "success" ? <ProgressStepper currentIndex={stageIndex} /> : null}{message ? <Notice tone="success">{message}</Notice> : null}{error ? <Notice tone="error">{error}</Notice> : null}<AnimatePresence mode="wait"><motion.section key={stage} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: reduceMotion ? 0 : 10 }} initial={{ opacity: 0, y: reduceMotion ? 0 : 10 }} transition={{ duration: reduceMotion ? 0 : transition.duration }}>{content}</motion.section></AnimatePresence>{stage !== "welcome" && stage !== "success" ? <div className="mt-5 text-center"><Button disabled={pending} onClick={() => invoke(async () => { const result = await abandonEventDemoSession(publicCode); if (result.status === "success") { setSession(null); setPreviewUrl(null); setProfilePublicId(null); setStage("welcome"); } return result; })} variant="ghost">Cancel demo</Button></div> : null}</div></main>;

  if (stage === "welcome") return shell(<Welcome pending={pending} onStart={() => invoke(() => startEventDemoSession(publicCode))} />);
  if (stage === "pet") return shell(<StepCard eyebrow="Step 1 of 4" title="Tell us about your pet" description="These details help someone recognise them quickly if they are found."><PetStep initial={session} pending={pending} onSubmit={(value) => invoke(async () => { const result = await updateEventDemoPetDetails(publicCode, value); if (result.status === "success") setSession((current) => ({ ...current, ...value } as Session)); return result; })} /></StepCard>);
  if (stage === "photo") return shell(<StepCard eyebrow="Step 2 of 4" title="Add a photo they will recognise" description="A clear, friendly photo makes your temporary profile feel familiar and trustworthy."><PhotoStep pending={pending} previewUrl={previewUrl} onBack={() => setStage("pet")} onContinueSaved={() => setStage("privacy")} onSubmit={(data) => invoke(() => uploadEventDemoPhoto(publicCode, data))} /></StepCard>);
  if (stage === "privacy") return shell(<StepCard eyebrow="Step 3 of 4" title="Stay in control of your privacy" description="Only the details you explicitly choose will appear on the public profile."><PrivacyStep initial={session} pending={pending} onBack={() => setStage("photo")} onSubmit={(value) => invoke(async () => { const result = await updateEventDemoContactAndPrivacy(publicCode, value); if (result.status === "success") setSession((current) => ({ ...current, contactTelephone: value.contactTelephone, contactEmail: value.contactEmail, ...value.visibility } as Session)); return result; })} /></StepCard>);
  if (stage === "preview") return shell(<StepCard eyebrow="Step 4 of 4" title="Review your PetTap profile" description="Take a moment to check what a finder will see before making it live."><PreviewStep pending={pending} previewUrl={previewUrl} session={session} onBack={() => setStage("privacy")} onComplete={() => invoke(() => completeEventDemoProfile(publicCode))} onRefresh={() => invoke(() => getEventDemoPreview(publicCode))} /></StepCard>);
  return shell(<Success profilePublicId={profilePublicId} pending={pending} onCancel={() => invoke(() => abandonEventDemoSession(publicCode))} onReview={() => setStage("preview")} />);
}

function ActivationHeader() { return <header className="mb-6 flex items-center justify-between rounded-2xl border border-white bg-[#07152e] px-5 py-4 text-white shadow-[0_10px_28px_rgba(7,21,46,0.12)]"><span className="inline-flex items-center gap-2 text-xl font-semibold"><PawPrint aria-hidden="true" className="size-6" />pettap</span><span className="inline-flex items-center gap-2 rounded-full border border-white/20 px-3 py-1.5 text-xs font-semibold tracking-wide text-[#ffb45e]"><Sparkles aria-hidden="true" className="size-3.5" />LIVE EVENT DEMO</span></header>; }
function ProgressStepper({ currentIndex }: { currentIndex: number }) { return <nav aria-label="Activation progress" className="mb-6 rounded-2xl border border-neutral-200 bg-white px-4 py-4 shadow-sm sm:px-6"><ol className="grid grid-cols-4 gap-2">{steps.map((item, index) => { const complete = index < currentIndex; const current = index === currentIndex; return <li aria-current={current ? "step" : undefined} className="min-w-0" key={item.id}><div className="flex items-center gap-2"><span className={`flex size-7 shrink-0 items-center justify-center rounded-full text-xs font-bold ${complete ? "bg-[#075a24] text-white" : current ? "bg-[#ff7900] text-white" : "bg-neutral-100 text-neutral-500"}`}>{complete ? <Check aria-hidden="true" className="size-4" /> : index + 1}</span><span className={`hidden truncate text-sm font-semibold sm:block ${current ? "text-[#07152e]" : "text-neutral-500"}`}>{item.label}</span></div><p className="mt-2 hidden text-xs text-neutral-500 lg:block">{item.description}</p></li>; })}</ol></nav>; }
function Notice({ children, tone }: { children: React.ReactNode; tone: "success" | "error" }) { return <p aria-live="polite" className={`mb-5 rounded-2xl border px-4 py-3 text-sm ${tone === "success" ? "border-emerald-100 bg-emerald-50 text-emerald-900" : "border-red-100 bg-red-50 text-red-800"}`}>{children}</p>; }
function StepCard({ eyebrow, title, description, children }: { eyebrow: string; title: string; description: string; children: React.ReactNode }) { return <Card className="overflow-hidden p-5 sm:p-8" variant="elevated"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#ff7900]">{eyebrow}</p><h1 className="mt-3 text-3xl font-bold tracking-[-0.04em] sm:text-4xl">{title}</h1><p className="mt-3 max-w-xl text-base leading-7 text-[#4c5870]">{description}</p>{children}</Card>; }
function Welcome({ pending, onStart }: { pending: boolean; onStart: () => void }) { return <Card className="overflow-hidden p-6 sm:p-10" variant="elevated"><div className="flex size-14 items-center justify-center rounded-2xl bg-[#fff4e7] text-[#ff7900]"><PawPrint aria-hidden="true" className="size-7" /></div><p className="mt-7 text-xs font-bold uppercase tracking-[0.18em] text-[#ff7900]">A few minutes to safer journeys</p><h1 className="mt-3 max-w-xl text-4xl font-bold leading-[1.03] tracking-[-0.055em] sm:text-5xl">Let’s create a profile that helps bring them home.</h1><p className="mt-5 max-w-xl text-lg leading-8 text-[#4c5870]">Set up your temporary PetTap profile in four simple steps. You choose what is shared, and it is automatically removed after this live event demo.</p><div className="mt-8 grid gap-3 rounded-2xl bg-[#f7f8fa] p-4 text-sm text-[#25314a] sm:grid-cols-2"><span className="inline-flex items-center gap-2"><ShieldCheck aria-hidden="true" className="size-5 text-[#075a24]" />Your information stays private</span><span className="inline-flex items-center gap-2"><LockKeyhole aria-hidden="true" className="size-5 text-[#075a24]" />No home address required</span></div><Button className="mt-8 min-h-12 rounded-xl bg-[#07152e] px-5 hover:bg-[#162646]" disabled={pending} loading={pending} onClick={onStart} rightIcon={<ChevronRight />} size="lg">Start the experience</Button><p className="mt-4 text-sm text-neutral-500">Usually takes less than two minutes.</p></Card>; }

function PetStep({ initial, onSubmit, pending }: { initial: Session | null; onSubmit: (value: Record<string, unknown>) => void; pending: boolean }) { return <form className="mt-8 space-y-5" onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); onSubmit({ petName: data.get("petName"), species: data.get("species"), breed: data.get("breed"), age: data.get("age"), personality: data.get("personality"), ownerFirstName: data.get("ownerFirstName") }); }}><Field autoComplete="off" defaultValue={initial?.petName ?? ""} label="Pet name" maxLength={60} name="petName" required /><Select defaultValue={initial?.species ?? ""} label="Species" name="species" required><option disabled value="">Choose species</option><option value="dog">Dog</option><option value="cat">Cat</option><option value="other">Other</option></Select><div className="grid gap-5 sm:grid-cols-2"><Field defaultValue={initial?.breed ?? ""} label="Breed (optional)" maxLength={80} name="breed" /><Field defaultValue={initial?.age ?? ""} label="Age (optional)" maxLength={40} name="age" /></div><Field defaultValue={initial?.personality ?? ""} label="Personality (optional)" maxLength={240} name="personality" placeholder="Friendly, curious, a little shy…" /><Field autoComplete="given-name" defaultValue={initial?.ownerFirstName ?? ""} label="Your first name (optional)" maxLength={80} name="ownerFirstName" /><ActionRow pending={pending} submitLabel="Continue to photo" /></form>; }

function PhotoStep({ onSubmit, onBack, onContinueSaved, pending, previewUrl }: { onSubmit: (data: FormData) => void; onBack: () => void; onContinueSaved: () => void; pending: boolean; previewUrl: string | null }) {
  const takePhotoInput = useRef<HTMLInputElement>(null); const galleryInput = useRef<HTMLInputElement>(null); const objectUrl = useRef<string | null>(null);
  const [photo, setPhoto] = useState<File | null>(null); const [localPreview, setLocalPreview] = useState<string | null>(null); const [selectionError, setSelectionError] = useState<string | null>(null);
  function selectPhoto(file: File | undefined, input: HTMLInputElement) { input.value = ""; if (!file) return; if (!eventDemoPhotoTypes.has(file.type)) { setPhoto(null); setSelectionError("Choose a JPG, PNG, WebP, HEIC or HEIF image."); return; } if (file.size <= 0 || file.size > MAX_EVENT_DEMO_PHOTO_SIZE) { setPhoto(null); setSelectionError("Choose an image smaller than 6 MB."); return; } if (objectUrl.current) URL.revokeObjectURL(objectUrl.current); objectUrl.current = URL.createObjectURL(file); setLocalPreview(objectUrl.current); setSelectionError(null); setPhoto(file); }
  function removePhoto() { if (objectUrl.current) URL.revokeObjectURL(objectUrl.current); objectUrl.current = null; setLocalPreview(null); setPhoto(null); }
  function submitPhoto(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!photo) { if (previewUrl) { onContinueSaved(); return; } setSelectionError("Choose a photo before saving."); return; } const data = new FormData(); data.set("photo", photo); onSubmit(data); }
  const image = localPreview ?? previewUrl;
  return <form className="mt-8 space-y-5" onSubmit={submitPhoto}><div className="overflow-hidden rounded-[24px] border border-neutral-200 bg-neutral-50"><div className="relative aspect-[4/3]">{image ? <Image alt="Private preview of your pet" className="object-cover" fill sizes="(max-width: 768px) 100vw, 620px" src={image} unoptimized /> : <div className="flex h-full flex-col items-center justify-center p-6 text-center"><span className="flex size-14 items-center justify-center rounded-2xl bg-white text-[#ff7900] shadow-sm"><ImagePlus aria-hidden="true" className="size-7" /></span><p className="mt-4 font-semibold">A clear photo helps people recognise your pet.</p><p className="mt-1 text-sm text-neutral-500">Keep their face and collar visible if you can.</p></div>}</div>{image ? <div className="flex items-center justify-between border-t border-neutral-200 bg-white px-4 py-3"><p className="truncate text-sm font-medium text-neutral-700">{photo ? photo.name : "Saved pet photo"}</p><Button disabled={pending} onClick={removePhoto} type="button" variant="ghost">Remove</Button></div> : null}</div><p className="text-sm leading-6 text-[#4c5870]">JPG, PNG, WebP, HEIC or HEIF. Up to 6 MB. Your photo is stored privately and is deleted with this temporary demo.</p><input accept="image/*" aria-label="Take a photo of your pet" capture="environment" className="sr-only" onChange={(event) => selectPhoto(event.currentTarget.files?.[0], event.currentTarget)} ref={takePhotoInput} type="file" /><input accept="image/*" aria-label="Choose a pet photo from your gallery" className="sr-only" onChange={(event) => selectPhoto(event.currentTarget.files?.[0], event.currentTarget)} ref={galleryInput} type="file" /><div className="grid gap-3 sm:grid-cols-2"><Button disabled={pending} leftIcon={<Camera />} onClick={() => takePhotoInput.current?.click()} type="button" variant="outline">Take a photo</Button><Button disabled={pending} leftIcon={<ImagePlus />} onClick={() => galleryInput.current?.click()} type="button" variant="outline">Choose from gallery</Button></div>{selectionError ? <p className="text-sm text-red-700" role="alert">{selectionError}</p> : null}<ActionRow backLabel="Back" onBack={onBack} pending={pending} submitDisabled={!photo && !previewUrl} submitLabel={photo ? "Save photo" : "Continue"} /></form>;
}

function PrivacyStep({ initial, onSubmit, onBack, pending }: { initial: Session | null; onSubmit: (value: PrivacyFormValue) => void; onBack: () => void; pending: boolean }) { const choices = [["showOwnerFirstName", "Show my first name"], ["showTelephone", "Show telephone"], ["showEmail", "Show email"], ["showBreed", "Show breed"], ["showAge", "Show age"], ["showPersonality", "Show personality"]] as const; return <form className="mt-8 space-y-5" onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); const visibility = { showOwnerFirstName: data.get("showOwnerFirstName") === "on", showTelephone: data.get("showTelephone") === "on", showEmail: data.get("showEmail") === "on", showBreed: data.get("showBreed") === "on", showAge: data.get("showAge") === "on", showPersonality: data.get("showPersonality") === "on" }; onSubmit({ contactTelephone: String(data.get("contactTelephone") ?? "") || null, contactEmail: String(data.get("contactEmail") ?? "") || null, visibility, demoConsentAccepted: data.get("demoConsentAccepted") === "on", marketingConsent: data.get("marketingConsent") === "on" }); }}><div className="grid gap-5 sm:grid-cols-2"><Field autoComplete="tel" defaultValue={initial?.contactTelephone ?? ""} label="Telephone (optional)" maxLength={40} name="contactTelephone" type="tel" /><Field autoComplete="email" defaultValue={initial?.contactEmail ?? ""} label="Email (optional)" maxLength={254} name="contactEmail" type="email" /></div><fieldset className="rounded-2xl border border-neutral-200 p-4"><legend className="px-1 text-sm font-semibold">Choose what people can see</legend><div className="mt-3 grid gap-3 sm:grid-cols-2">{choices.map(([name, label]) => <label className="flex min-h-11 items-center gap-3 rounded-xl px-2 text-sm text-[#25314a] hover:bg-neutral-50" key={name}><input defaultChecked={Boolean(initial?.[name])} name={name} type="checkbox" /><span>{label}</span></label>)}</div></fieldset><label className="flex gap-3 rounded-2xl bg-[#f7f8fa] p-4 text-sm leading-6"><input className="mt-1" name="demoConsentAccepted" required type="checkbox" /><span>I understand this is a temporary event demonstration and my demo data will be deleted automatically.</span></label><label className="flex gap-3 px-1 text-sm leading-6"><input className="mt-1" name="marketingConsent" type="checkbox" /><span>I would like to receive PetTap launch news and updates.</span></label><ActionRow backLabel="Back" onBack={onBack} pending={pending} submitLabel="Review profile" /></form>; }

function PreviewStep({ session, previewUrl, pending, onBack, onRefresh, onComplete }: { session: Session | null; previewUrl: string | null; pending: boolean; onBack: () => void; onRefresh: () => void; onComplete: () => void }) { return <div className="mt-8 space-y-5"><div className="grid gap-5 rounded-[24px] border border-neutral-200 bg-[#f7f8fa] p-4 sm:grid-cols-[180px_1fr] sm:p-5">{previewUrl ? <Image alt="Private preview of your pet" className="aspect-square rounded-2xl object-cover" height={360} src={previewUrl} unoptimized width={360} /> : <button className="flex aspect-square items-center justify-center rounded-2xl bg-white text-sm font-semibold text-[#07152e] shadow-sm" disabled={pending} onClick={onRefresh} type="button">Load photo preview</button>}<div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#ff7900]">Public profile preview</p><h2 className="mt-2 text-3xl font-bold">{session?.petName ?? "Your pet"}</h2><p className="mt-2 capitalize text-neutral-500">{session?.species ?? "Pet"}</p>{session?.showBreed && session.breed ? <p className="mt-4 text-sm"><span className="text-neutral-500">Breed</span><br /><strong>{session.breed}</strong></p> : null}{session?.showAge && session.age ? <p className="mt-3 text-sm"><span className="text-neutral-500">Age</span><br /><strong>{session.age}</strong></p> : null}{session?.showPersonality && session.personality ? <p className="mt-3 text-sm"><span className="text-neutral-500">Personality</span><br /><strong>{session.personality}</strong></p> : null}{session?.showTelephone || session?.showEmail ? <p className="mt-3 text-sm text-[#075a24]"><strong>Contact details shared</strong></p> : null}</div></div><div className="rounded-2xl border border-[#d8eadc] bg-[#f2f9f3] p-4 text-sm leading-6 text-[#214d2a]"><ShieldCheck aria-hidden="true" className="mr-2 inline size-4" /><strong>Private by design.</strong> Only your selected details will appear. Your address and session information are never public.</div><ActionRow backLabel="Back and edit" onBack={onBack} pending={pending} submitLabel="Create my demo profile" onSubmit={onComplete} /></div>; }
function Success({ profilePublicId, pending, onCancel, onReview }: { profilePublicId: string | null; pending: boolean; onCancel: () => void; onReview: () => void }) { return <Card className="p-7 text-center sm:p-10" variant="elevated"><motion.span animate={{ scale: 1 }} className="mx-auto flex size-16 items-center justify-center rounded-3xl bg-[#e8f6eb] text-[#075a24]" initial={{ scale: 0.8 }} transition={transition}><Check aria-hidden="true" className="size-8" /></motion.span><p className="mt-7 text-xs font-bold uppercase tracking-[0.18em] text-[#075a24]">Tag activated</p><h1 className="mt-3 text-4xl font-bold tracking-[-0.05em]">Your PetTap profile is ready.</h1><p className="mx-auto mt-4 max-w-lg text-lg leading-8 text-[#4c5870]">Your temporary profile is live. Try tapping the tag again to see the safe, friendly profile a finder would see.</p>{profilePublicId ? <a className="mt-8 inline-flex min-h-12 items-center justify-center rounded-xl bg-[#07152e] px-5 text-sm font-semibold text-white hover:bg-[#162646]" href={`/event/profile/${profilePublicId}`}>Open public profile</a> : null}<div className="mt-7 rounded-2xl bg-[#f7f8fa] p-4 text-left text-sm leading-6 text-[#4c5870]"><strong className="block text-[#07152e]">What happens next</strong><span>Keep the tag close to your phone and tap it again to test the finder experience. Your demo data is removed automatically after the event.</span></div><div className="mt-6 flex flex-col justify-center gap-3 sm:flex-row"><Button disabled={pending} onClick={onReview} variant="outline">Review profile</Button><Button disabled={pending} onClick={onCancel} variant="ghost">Cancel and remove my demo</Button></div></Card>; }
function ActionRow({ backLabel, onBack, onSubmit, pending, submitLabel, submitDisabled }: { backLabel?: string; onBack?: () => void; onSubmit?: () => void; pending: boolean; submitLabel: string; submitDisabled?: boolean }) { return <div className="flex flex-col-reverse gap-3 pt-2 sm:flex-row sm:justify-between">{onBack ? <Button disabled={pending} leftIcon={<ChevronLeft />} onClick={onBack} type="button" variant="outline">{backLabel ?? "Back"}</Button> : <span />}{onSubmit ? <Button disabled={pending || submitDisabled} loading={pending} onClick={onSubmit} rightIcon={<ChevronRight />}>{submitLabel}</Button> : <Button disabled={pending || submitDisabled} fullWidth={false} loading={pending} rightIcon={<ChevronRight />} type="submit">{submitLabel}</Button>}</div>; }
function Field({ label, name, ...props }: { label: string; name: string } & React.InputHTMLAttributes<HTMLInputElement>) { return <label className="block text-sm font-semibold text-[#25314a]">{label}<input className="mt-2 min-h-12 w-full rounded-xl border border-neutral-200 bg-white px-3 text-base font-normal outline-none transition focus:border-[#07152e] focus:ring-4 focus:ring-[#07152e]/10 disabled:bg-neutral-100" name={name} {...props} /></label>; }
function Select({ children, label, name, ...props }: { children: React.ReactNode; label: string; name: string } & React.SelectHTMLAttributes<HTMLSelectElement>) { return <label className="block text-sm font-semibold text-[#25314a]">{label}<select className="mt-2 min-h-12 w-full rounded-xl border border-neutral-200 bg-white px-3 text-base font-normal outline-none transition focus:border-[#07152e] focus:ring-4 focus:ring-[#07152e]/10" name={name} {...props}>{children}</select></label>; }
