import Link from "next/link";
import { Activity, ArrowUpRight, Box, PackageCheck, PoundSterling, ShoppingBag, Truck } from "lucide-react";

import { formatAdminMoney } from "../orders/services/admin-order-domain";
import { AdminDashboardService, formatOperationalDuration } from "../dashboard/services/admin-dashboard-service";
import type { AdminDashboardViewModel, DashboardPeriod } from "../dashboard/types";
import type { AdminContextViewModel } from "../types/admin";

const statusLabels: Record<string, string> = { paid: "Paid", inProduction: "In production", printed: "Printed / ready", packed: "Packed", shipped: "Shipped", delivered: "Delivered", cancelled: "Cancelled" };

function MetricCard({ label, value, detail, icon: Icon }: { label: string; value: string; detail: string; icon: typeof PoundSterling }) {
  return <article className="rounded-[28px] border border-black/[0.07] bg-white p-5 shadow-[0_12px_36px_rgba(0,0,0,0.04)] sm:p-6"><div className="flex items-start justify-between gap-3"><p className="text-sm font-medium text-neutral-500">{label}</p><span className="rounded-xl bg-neutral-100 p-2 text-neutral-700"><Icon className="size-4" aria-hidden="true" /></span></div><p className="mt-5 text-3xl font-semibold tracking-[-0.05em] text-neutral-950">{value}</p><p className="mt-2 text-sm text-neutral-500">{detail}</p></article>;
}

function Panel({ title, description, children, action }: { title: string; description?: string; children: React.ReactNode; action?: React.ReactNode }) {
  return <section className="rounded-[28px] border border-black/[0.07] bg-white p-5 shadow-[0_12px_36px_rgba(0,0,0,0.04)] sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold tracking-[-0.03em]">{title}</h2>{description ? <p className="mt-1 text-sm text-neutral-500">{description}</p> : null}</div>{action}</div><div className="mt-6">{children}</div></section>;
}

function RevenueChart({ dashboard }: { dashboard: AdminDashboardViewModel }) {
  const maximum = Math.max(1, ...dashboard.revenueSeries.map((point) => point.revenueMinor));
  return <div className="flex h-52 items-end gap-1.5 sm:gap-2" aria-label={`Revenue over the last ${dashboard.period}`} role="img">
    {dashboard.revenueSeries.length ? dashboard.revenueSeries.map((point) => <div className="group flex h-full min-w-0 flex-1 items-end" key={point.day} title={`${point.day}: ${formatAdminMoney(point.revenueMinor, "GBP")}`}><div className="w-full rounded-t-md bg-neutral-950 transition-colors group-hover:bg-neutral-700" style={{ height: `${Math.max(3, Math.round((point.revenueMinor / maximum) * 100))}%` }} /></div>) : <p className="m-auto text-sm text-neutral-500">Revenue will appear here as payments are received.</p>}
  </div>;
}

function OperationsChart({ dashboard }: { dashboard: AdminDashboardViewModel }) {
  const maximum = Math.max(1, ...dashboard.orderSeries.flatMap((point) => [point.payments, point.production, point.shipped, point.delivered]));
  const metrics = [["Payments", "bg-neutral-950", "payments"], ["Production", "bg-amber-500", "production"], ["Shipped", "bg-sky-600", "shipped"], ["Delivered", "bg-emerald-600", "delivered"]] as const;
  return <div><div className="mb-5 flex flex-wrap gap-x-4 gap-y-2 text-xs text-neutral-600">{metrics.map(([label, colour]) => <span className="inline-flex items-center gap-2" key={label}><i className={`size-2 rounded-full ${colour}`} aria-hidden="true" />{label}</span>)}</div><div className="flex h-52 items-end gap-1.5 sm:gap-2" aria-label={`Operational events over the last ${dashboard.period}`} role="img">{dashboard.orderSeries.length ? dashboard.orderSeries.map((point) => <div className="flex h-full min-w-0 flex-1 items-end gap-px" key={point.day}>{metrics.map(([, colour, key]) => <div className={`flex-1 rounded-t-sm ${colour}`} key={key} style={{ height: `${Math.max(2, Math.round((point[key] / maximum) * 100))}%` }} title={`${point.day}: ${point[key]} ${key}`} />)}</div>) : <p className="m-auto text-sm text-neutral-500">Operational activity will appear here as orders progress.</p>}</div></div>;
}

function Rankings({ title, items }: { title: string; items: AdminDashboardViewModel["rankings"]["sizes"] }) {
  const maximum = Math.max(1, ...items.map((item) => item.quantity));
  return <div><h3 className="text-sm font-semibold">{title}</h3>{items.length ? <ol className="mt-4 space-y-3">{items.map((item) => <li key={item.label}><div className="mb-1.5 flex justify-between gap-3 text-sm"><span className="truncate">{item.label}</span><span className="font-medium tabular-nums">{item.quantity}</span></div><div className="h-1.5 overflow-hidden rounded-full bg-neutral-100"><div className="h-full rounded-full bg-neutral-900" style={{ width: `${(item.quantity / maximum) * 100}%` }} /></div></li>)}</ol> : <p className="mt-4 text-sm text-neutral-500">No product data yet.</p>}</div>;
}

export async function AdminDashboard({ context, period = "30d" }: { context: AdminContextViewModel; period?: DashboardPeriod }) {
  const dashboard = await new AdminDashboardService().getDashboard(period);
  const statusTotal = Math.max(1, dashboard.statusTotal);
  const periodLinks: Array<[DashboardPeriod, string]> = [["7d", "7 days"], ["30d", "30 days"], ["90d", "90 days"]];

  return <>
    <header className="max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-neutral-500">Private operations area</p><h1 className="mt-3 text-3xl font-semibold tracking-[-0.05em] sm:text-5xl">Business overview</h1><p className="mt-4 text-base leading-7 text-neutral-600">A live, privacy-conscious view for {context.role.replaceAll("_", " ")} access.</p></header>

    <section className="mt-10"><div className="mb-4 flex items-center gap-2"><PoundSterling className="size-4" aria-hidden="true" /><h2 className="text-sm font-semibold uppercase tracking-[0.12em] text-neutral-600">Revenue</h2></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Revenue today" value={formatAdminMoney(dashboard.revenue.today, "GBP")} detail="Paid orders today" icon={PoundSterling} /><MetricCard label="Last 7 days" value={formatAdminMoney(dashboard.revenue.last7Days, "GBP")} detail="Paid order revenue" icon={PoundSterling} /><MetricCard label="Last 30 days" value={formatAdminMoney(dashboard.revenue.last30Days, "GBP")} detail="Paid order revenue" icon={PoundSterling} /><MetricCard label="Total revenue" value={formatAdminMoney(dashboard.revenue.total, "GBP")} detail="Excludes cancelled and refunded orders" icon={PoundSterling} /></div></section>

    <section className="mt-10"><div className="mb-4 flex items-center gap-2"><ShoppingBag className="size-4" aria-hidden="true" /><h2 className="text-sm font-semibold uppercase tracking-[0.12em] text-neutral-600">Orders</h2></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Orders today" value={String(dashboard.orders.today)} detail="Created today" icon={ShoppingBag} /><MetricCard label="Last 7 days" value={String(dashboard.orders.last7Days)} detail="Orders created" icon={ShoppingBag} /><MetricCard label="Last 30 days" value={String(dashboard.orders.last30Days)} detail="Orders created" icon={ShoppingBag} /><MetricCard label="Total orders" value={String(dashboard.orders.total)} detail="All order states" icon={ShoppingBag} /></div></section>

    <section className="mt-10 grid gap-4 lg:grid-cols-[1.35fr_1fr]"><Panel title="Revenue over time" description="Paid revenue, excluding cancelled and refunded orders." action={<div className="flex rounded-xl bg-neutral-100 p-1">{periodLinks.map(([value, label]) => <Link className={`rounded-lg px-2.5 py-1.5 text-xs font-semibold transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-neutral-950 ${dashboard.period === value ? "bg-white text-neutral-950 shadow-sm" : "text-neutral-500 hover:text-neutral-950"}`} href={`/admin?period=${value}`} key={value}>{label}</Link>)}</div>}><RevenueChart dashboard={dashboard} /></Panel><Panel title="Order conversion" description="Current order lifecycle mix."><div className="space-y-3">{dashboard.statuses.map((status) => <div key={status.key}><div className="mb-1.5 flex justify-between gap-4 text-sm"><span>{statusLabels[status.key] ?? status.key}</span><span className="tabular-nums text-neutral-500">{status.value} · {Math.round((status.value / statusTotal) * 100)}%</span></div><div className="h-2 overflow-hidden rounded-full bg-neutral-100"><div className="h-full rounded-full bg-neutral-950" style={{ width: `${Math.round((status.value / statusTotal) * 100)}%` }} /></div></div>)}</div></Panel></section>

    <section className="mt-4 grid gap-4 lg:grid-cols-2"><Panel title="Operational flow" description="Orders created during the selected period."><OperationsChart dashboard={dashboard} /></Panel><Panel title="Production now" description="Current queue across operations."><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{[["Waiting production", dashboard.production.waitingProduction], ["Printing", dashboard.production.printing], ["Waiting packing", dashboard.production.waitingPacking], ["Waiting shipping", dashboard.production.waitingShipping], ["Delivered today", dashboard.production.deliveredToday]].map(([label, value]) => <div className="rounded-2xl bg-neutral-50 p-4" key={String(label)}><p className="text-xs font-medium text-neutral-500">{label}</p><p className="mt-2 text-2xl font-semibold tracking-[-0.04em]">{value}</p></div>)}</div></Panel></section>

    <section className="mt-4 grid gap-4 lg:grid-cols-[1.2fr_1fr]"><Panel title="Average time between stages" description="Based on persisted lifecycle history; stages without enough records stay empty."><dl className="divide-y divide-black/[0.06]">{dashboard.durations.map((item) => <div className="flex items-center justify-between gap-4 py-3 first:pt-0 last:pb-0" key={item.label}><dt className="text-sm text-neutral-600">{item.label}</dt><dd className="font-semibold tabular-nums">{formatOperationalDuration(item.hours)}</dd></div>)}</dl></Panel><Panel title="Inventory" description="Prepared for future consumable tracking."><div className="flex min-h-48 flex-col items-center justify-center rounded-2xl border border-dashed border-black/[0.12] bg-neutral-50 p-6 text-center"><Box className="size-6 text-neutral-500" aria-hidden="true" /><p className="mt-3 font-semibold">Inventory tracking coming soon.</p><p className="mt-1 max-w-xs text-sm leading-6 text-neutral-500">NFC tags, filament and packaging will appear here when stock controls are introduced.</p></div></Panel></section>

    <section className="mt-4 grid gap-4 xl:grid-cols-3"><Panel title="Top sizes"><Rankings title="Most selected" items={dashboard.rankings.sizes} /></Panel><Panel title="Top designs"><Rankings title="Most selected" items={dashboard.rankings.designs} /></Panel><Panel title="Top colours"><Rankings title="Most selected" items={dashboard.rankings.colours} /></Panel></section>

    <section className="mt-4 grid gap-4 lg:grid-cols-[1.35fr_1fr]"><Panel title="Recent activity" description="Latest operational events; customer details are intentionally excluded." action={<Activity className="size-4 text-neutral-500" aria-hidden="true" />}>{dashboard.activity.length ? <ol className="divide-y divide-black/[0.06]">{dashboard.activity.map((item) => <li className="flex items-start justify-between gap-4 py-3 first:pt-0" key={`${item.action}-${item.occurredAt}`}><div><p className="text-sm font-medium text-neutral-900">{item.action.replaceAll(".", " · ")}</p><p className="mt-1 text-xs text-neutral-500">{item.targetType} · {item.result}</p></div><time className="shrink-0 text-xs text-neutral-500" dateTime={item.occurredAt}>{new Intl.DateTimeFormat("en-GB", { day: "numeric", month: "short", hour: "2-digit", minute: "2-digit" }).format(new Date(item.occurredAt))}</time></li>)}</ol> : <p className="py-10 text-center text-sm text-neutral-500">Operational events will appear here as your team works through orders.</p>}</Panel><Panel title="Quick access"><div className="space-y-2"><Link href="/admin/orders" className="flex min-h-12 items-center justify-between rounded-xl bg-neutral-950 px-4 text-sm font-semibold text-white transition hover:bg-neutral-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-neutral-950">Review orders <ArrowUpRight className="size-4" aria-hidden="true" /></Link><Link href="/admin/production" className="flex min-h-12 items-center justify-between rounded-xl border border-black/[0.08] px-4 text-sm font-semibold transition hover:bg-neutral-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-neutral-950">Production centre <PackageCheck className="size-4" aria-hidden="true" /></Link><Link href="/admin/shipping" className="flex min-h-12 items-center justify-between rounded-xl border border-black/[0.08] px-4 text-sm font-semibold transition hover:bg-neutral-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-neutral-950">Shipping centre <Truck className="size-4" aria-hidden="true" /></Link></div></Panel></section>
  </>;
}
