import { headers } from "next/headers";
import Image from "next/image";
import { PublicTagResolverService } from "@/features/nfc/services/public-tag-resolver-service";
import { presentPublicLostPage } from "@/features/nfc/public-lost-page-presenter";
import { PublicContactRequestForm } from "@/features/contact-requests/components/public-contact-request-form";
export const metadata={robots:{index:false,follow:false}};
export const dynamic="force-dynamic";
export const revalidate=0;
export default async function Page({params}:{params:Promise<{publicCode:string}>}){const {publicCode}=await params;const ip=(await headers()).get("x-forwarded-for")?.split(",")[0]?.trim()??"unknown";const r=await new PublicTagResolverService().resolveByPublicCode({publicCode,ip});if(r.state==="lost"){const view=presentPublicLostPage(r.profile);return <main className="mx-auto max-w-lg px-6 py-12"><p className="text-sm font-semibold uppercase tracking-[.16em] text-rose-700">{view.eyebrow}</p><h1 className="mt-3 text-3xl font-semibold tracking-tight">{view.headline}</h1><p className="mt-3 text-neutral-600">{view.safetyMessage}</p>{view.photoUrl?<Image className="mt-7 aspect-[4/3] w-full rounded-3xl object-cover" src={view.photoUrl} alt={view.name??"Reported missing pet"} width={800} height={600} unoptimized/>:null}<section className="mt-7 rounded-3xl border border-neutral-200 p-6"><h2 className="text-xl font-semibold">{view.name??view.genericPetLabel}</h2>{view.species?<p className="mt-1 text-neutral-600">{view.species}</p>:null}{view.reportedAt?<p className="mt-4 text-sm text-neutral-600">Reported missing since {view.reportedAt}</p>:null}</section><PublicContactRequestForm publicCode={publicCode}/></main>}if(r.state==="active")return <main><h1>{r.profile.name??"PetTap pet"}</h1><p>{r.profile.species}</p>{r.profile.photoUrl?<Image src={r.profile.photoUrl} alt="Pet" width={640} height={480} unoptimized/>:null}</main>;const message=r.state==="not_activated"?"This PetTap has not been configured yet.":"This PetTap is unavailable.";return <main><h1>PetTap</h1><p>{message}</p></main>}
