"use client";

import Link from "next/link";
import { useActionState, useState, useTransition } from "react";
import { CheckCircle2, Clipboard, ExternalLink, RefreshCw, ShieldAlert, Tag, Trash2 } from "lucide-react";

import { Button } from "@/components/ui/button";
import { createEventDemoTag, createEventDemoTagBatch, cleanupExpiredEventDemoSessions, resetEventDemoTag, setEventDemoTagEnabled, searchConsentedEventDemoLead, type EventDemoAdminActionState } from "../actions/event-demo-admin-actions";
import type { EventDemoAdminTagView, EventDemoLeadView, EventDemoSessionAdminView } from "../services/event-demo-admin-service";
import { eventDemoAdminUrl, type EventDemoAdminQuery } from "../services/event-demo-admin-query";

const initial: EventDemoAdminActionState | null = null;
const date = (value: string | null) => value ? new Intl.DateTimeFormat("en-GB", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—";
function badge(status: string) { const labels: Record<string, string> = { available: "Available", in_progress: "In use", completed: "Profile ready", expired: "Expired", disabled: "Disabled", started: "Started", profile_created: "Profile created", deleted: "Removed" }; return labels[status] ?? status; }

function Notice({ state }: { state: EventDemoAdminActionState | null }) { return state ? <p aria-live="polite" className={`rounded-xl px-4 py-3 text-sm ${state.status === "success" ? "bg-emerald-50 text-emerald-900" : "bg-red-50 text-red-900"}`}>{state.message}{state.activationUrls?.length ? <span className="mt-2 block break-all text-xs">{state.activationUrls.length === 1 ? state.activationUrls[0] : `${state.activationUrls.length} activation URLs are ready in the tag export.`}</span> : null}</p> : null; }
function Pager({ page, totalPages, total, name, query }: { page: number; totalPages: number; total: number; name: string; query: EventDemoAdminQuery }) { const key = name === "tags" ? "tagsPage" : name === "sessions" ? "sessionsPage" : "leadsPage"; const make = (n: number) => eventDemoAdminUrl(query, { [key]: String(n), section: name }); return <nav aria-label={`${name} pagination`} className="flex items-center justify-between gap-2 border-t border-black/[.07] px-5 py-4 text-sm"><span className="text-neutral-600">{total ? `Showing ${(page - 1) * 20 + 1}–${Math.min(page * 20, total)} of ${total}` : "Showing 0 of 0"}</span><div className="flex gap-2"><Link aria-label={`Previous ${name} page`} aria-disabled={page <= 1} className="rounded-lg border px-3 py-2 aria-disabled:pointer-events-none aria-disabled:opacity-40" href={make(Math.max(1, page - 1))}>Previous</Link><span className="py-2">Page {page} of {totalPages}</span><Link aria-label={`Next ${name} page`} aria-disabled={page >= totalPages} className="rounded-lg border px-3 py-2 aria-disabled:pointer-events-none aria-disabled:opacity-40" href={make(Math.min(totalPages, page + 1))}>Next</Link></div></nav>; }
function LeadSearch() { const [state, action, pending] = useActionState(searchConsentedEventDemoLead, null); const [show, setShow] = useState(true); return <form action={action} className="border-b p-4"><div className="flex gap-2"><label className="sr-only" htmlFor="lead-search">Search consented lead by email</label><input id="lead-search" name="email" required type="email" autoComplete="off" className="min-h-10 flex-1 rounded-xl border px-3" placeholder="Search consented lead by email" /><Button type="submit" loading={pending} variant="outline">Search privately</Button></div>{show && state ? <div tabIndex={-1} className="mt-3 rounded-xl bg-neutral-50 p-3 text-sm" aria-live="polite"><p>{state.message}</p>{state.lead ? <p className="mt-1 text-neutral-600">{state.lead.firstName ?? "Launch contact"} · {state.lead.email} · {state.lead.source}</p> : null}<button type="button" onClick={() => setShow(false)} className="mt-2 text-xs font-semibold underline">Clear search result</button></div> : null}</form>; }
function EventDemoFilters({ query }: { query: EventDemoAdminQuery }) { const hidden = (exclude: string[]) => Object.entries(query).filter(([key]) => !exclude.includes(key)).map(([key, value]) => <input key={key} type="hidden" name={key} value={value} />); return <section className="grid gap-4 lg:grid-cols-3" aria-label="Event demo filters">
  <form action="/admin/event-demo" className="rounded-2xl border border-black/[.07] bg-white p-4"><h2 className="font-semibold">Tag filters</h2>{hidden(["tagsPage", "tagStatus", "tagEnabled", "attentionOnly", "section"])}<input type="hidden" name="tagsPage" value="1" /><div className="mt-3 grid gap-2"><label className="text-sm font-medium">Status<select name="tagStatus" defaultValue={query.tagStatus ?? ""} className="mt-1 min-h-10 w-full rounded-xl border px-3"><option value="">All</option><option value="available">Available</option><option value="in_progress">In use</option><option value="completed">Profile ready</option><option value="expired">Expired</option><option value="disabled">Disabled</option></select></label><label className="text-sm font-medium">Enabled<select name="tagEnabled" defaultValue={query.tagEnabled ?? ""} className="mt-1 min-h-10 w-full rounded-xl border px-3"><option value="">All</option><option value="true">Enabled</option><option value="false">Disabled</option></select></label><label className="flex min-h-10 items-center gap-2 text-sm"><input type="checkbox" name="attentionOnly" value="true" defaultChecked={query.attentionOnly === "true"} />Needs attention only</label></div><div className="mt-3 flex gap-2"><Button type="submit" variant="outline">Apply filters</Button><Link className="rounded-xl px-3 py-2 text-sm font-semibold" href={eventDemoAdminUrl(query, { tagsPage: null, tagStatus: null, tagEnabled: null, attentionOnly: null })}>Clear tag filters</Link></div></form>
  <form action="/admin/event-demo" className="rounded-2xl border border-black/[.07] bg-white p-4"><h2 className="font-semibold">Session filters</h2>{hidden(["sessionsPage", "sessionStatus", "sessionTag", "sessionPeriod", "section"])}<input type="hidden" name="sessionsPage" value="1" /><input type="hidden" name="section" value="sessions" /><div className="mt-3 grid gap-2"><label className="text-sm font-medium">Status<select name="sessionStatus" defaultValue={query.sessionStatus ?? ""} className="mt-1 min-h-10 w-full rounded-xl border px-3"><option value="">All</option><option value="started">Started</option><option value="profile_created">Profile created</option><option value="completed">Completed</option><option value="expired">Expired</option><option value="deleted">Deleted</option></select></label><label className="text-sm font-medium">Period<select name="sessionPeriod" defaultValue={query.sessionPeriod ?? ""} className="mt-1 min-h-10 w-full rounded-xl border px-3"><option value="">All</option><option value="today">Today</option><option value="24h">Last 24 hours</option><option value="7d">Last 7 days</option></select></label></div><div className="mt-3 flex gap-2"><Button type="submit" variant="outline">Apply filters</Button><Link className="rounded-xl px-3 py-2 text-sm font-semibold" href={eventDemoAdminUrl(query, { sessionsPage: null, sessionStatus: null, sessionTag: null, sessionPeriod: null })}>Clear session filters</Link></div></form>
  <form action="/admin/event-demo" className="rounded-2xl border border-black/[.07] bg-white p-4"><h2 className="font-semibold">Lead filters</h2>{hidden(["leadsPage", "leadSource", "leadPeriod", "section"])}<input type="hidden" name="leadsPage" value="1" /><input type="hidden" name="section" value="leads" /><div className="mt-3 grid gap-2"><label className="text-sm font-medium">Source<select name="leadSource" defaultValue={query.leadSource ?? ""} className="mt-1 min-h-10 w-full rounded-xl border px-3"><option value="">All</option><option value="event_demo">Event demo</option><option value="fair">Fair</option></select></label><label className="text-sm font-medium">Consent period<select name="leadPeriod" defaultValue={query.leadPeriod ?? ""} className="mt-1 min-h-10 w-full rounded-xl border px-3"><option value="">All</option><option value="today">Today</option><option value="7d">Last 7 days</option><option value="30d">Last 30 days</option></select></label></div><div className="mt-3 flex gap-2"><Button type="submit" variant="outline">Apply filters</Button><Link className="rounded-xl px-3 py-2 text-sm font-semibold" href={eventDemoAdminUrl(query, { leadsPage: null, leadSource: null, leadPeriod: null })}>Clear lead filters</Link></div></form>
  </section>; }

function CreateTagForms({ canManage }: { canManage: boolean }) {
  const [single, singleAction, singlePending] = useActionState(createEventDemoTag, initial);
  const [batch, batchAction, batchPending] = useActionState(createEventDemoTagBatch, initial);
  if (!canManage) return null;
  return <section className="grid gap-4 lg:grid-cols-2" aria-label="Create demo tags">
    <form action={singleAction} className="rounded-3xl border border-black/[.07] bg-white p-5">
      <h2 className="font-semibold">Create demo tag</h2><p className="mt-1 text-sm text-neutral-600">Creates one NFC-first demo tag. Nothing is created until you submit.</p>
      <label className="mt-4 block text-sm font-medium" htmlFor="event-internal-name">Internal name<input required id="event-internal-name" name="internalName" maxLength={100} className="mt-2 min-h-11 w-full rounded-xl border border-black/10 px-3" placeholder="Fair Demo 01" /></label>
      <label className="mt-3 block text-sm font-medium" htmlFor="event-duration">Session duration (minutes)<input required defaultValue="60" min="10" max="240" id="event-duration" name="sessionDurationMinutes" type="number" className="mt-2 min-h-11 w-full rounded-xl border border-black/10 px-3" /></label>
      <Button className="mt-4" loading={singlePending} type="submit">Create tag</Button><div className="mt-3"><Notice state={single} /></div>
    </form>
    <form action={batchAction} className="rounded-3xl border border-black/[.07] bg-white p-5">
      <h2 className="font-semibold">Create small batch</h2><p className="mt-1 text-sm text-neutral-600">Up to 20 tags, named predictably for quick physical preparation.</p>
      <label className="mt-4 block text-sm font-medium" htmlFor="event-prefix">Name prefix<input required id="event-prefix" name="internalNamePrefix" maxLength={80} className="mt-2 min-h-11 w-full rounded-xl border border-black/10 px-3" placeholder="Fair Demo" /></label>
      <div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-sm font-medium" htmlFor="event-quantity">Quantity<input required defaultValue="5" min="1" max="20" id="event-quantity" name="quantity" type="number" className="mt-2 min-h-11 w-full rounded-xl border border-black/10 px-3" /></label><label className="text-sm font-medium" htmlFor="event-batch-duration">Minutes<input required defaultValue="60" min="10" max="240" id="event-batch-duration" name="sessionDurationMinutes" type="number" className="mt-2 min-h-11 w-full rounded-xl border border-black/10 px-3" /></label></div>
      <Button className="mt-4" loading={batchPending} type="submit">Create batch</Button><div className="mt-3"><Notice state={batch} /></div>
    </form>
  </section>;
}

function TagActions({ tag, canManage }: { tag: EventDemoAdminTagView; canManage: boolean }) {
  const [pending, start] = useTransition(); const [message, setMessage] = useState<string | null>(null);
  async function run(fn: () => Promise<EventDemoAdminActionState>) { start(async () => { const result = await fn(); setMessage(result.message); }); }
  async function copy() { const url = `${window.location.origin}/event/activate/${tag.publicCode}`; try { await navigator.clipboard.writeText(url); setMessage("Activation URL copied."); } catch { setMessage("Copy this activation URL: " + url); } }
  const resetLabel = tag.latestSession?.cleanupRequired ? "Retry cleanup" : "Reset";
  return <div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={copy} leftIcon={<Clipboard />}>Copy URL</Button><Link className="inline-flex min-h-7 items-center gap-1 rounded-lg border border-black/10 px-2.5 text-xs font-medium focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-neutral-950" href={`/event/activate/${tag.publicCode}`} target="_blank"><ExternalLink className="size-3" />Open</Link>{tag.latestSession?.profileAvailable ? <Link className="inline-flex min-h-7 items-center gap-1 rounded-lg border border-black/10 px-2.5 text-xs font-medium focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-neutral-950" href={`/event/profile/${tag.latestSession.publicId}`} target="_blank">Profile</Link> : null}{canManage ? <><Button size="sm" variant="outline" loading={pending} onClick={() => { if (window.confirm(`${resetLabel} for ${tag.internalName}? Temporary photo and profile data will be removed.`)) void run(() => resetEventDemoTag(tag.id)); }} leftIcon={<Trash2 />}>{resetLabel}</Button><Button size="sm" variant={tag.isEnabled ? "destructive" : "secondary"} loading={pending} onClick={() => { if (window.confirm(`${tag.isEnabled ? "Disable" : "Enable"} ${tag.internalName}?`)) void run(() => setEventDemoTagEnabled(tag.id, !tag.isEnabled)); }}>{tag.isEnabled ? "Disable" : "Enable"}</Button></> : null}{message ? <span aria-live="polite" className="basis-full text-xs text-neutral-600">{message}</span> : null}</div>;
}

export function EventDemoAdminConsole({ canManage, metrics, tags, sessions, leads, query }: { canManage: boolean; metrics: { totalTags: number; available: number; inProgress: number; completed: number; expired: number; disabled: number; sessionsStartedToday: number; profilesCompletedToday: number; profilesViewedToday: number; leadsConsentedToday: number; startedTotal: number; cleanupRequired: number; cleanupFailures: number }; tags: { total: number; page: number; totalPages: number; rows: EventDemoAdminTagView[] }; sessions: { total: number; page: number; totalPages: number; rows: EventDemoSessionAdminView[] }; leads: { total: number; page: number; totalPages: number; rows: EventDemoLeadView[] }; query: EventDemoAdminQuery }) {
  const [pending, start] = useTransition(); const [cleanupMessage, setCleanupMessage] = useState<string | null>(null);
  const completion = metrics.startedTotal ? Math.round((metrics.completed / metrics.startedTotal) * 100) : 0;
  return <div className="space-y-8">
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[["Tags", metrics.totalTags], ["Available", metrics.available], ["In use", metrics.inProgress], ["Profiles ready", metrics.completed], ["Needs attention", metrics.cleanupRequired + metrics.cleanupFailures]].map(([label, value]) => <article key={String(label)} className="rounded-2xl border border-black/[.07] bg-white p-4"><p className="text-xs font-semibold uppercase tracking-[.12em] text-neutral-500">{label}</p><p className="mt-2 text-3xl font-semibold tracking-[-.05em]">{value}</p></article>)}</section>
    <section className="rounded-3xl border border-black/[.07] bg-white p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-semibold">Quick actions</h2><p className="mt-1 text-sm text-neutral-600">Operational controls are private and audited.</p></div><div className="flex flex-wrap gap-2"><Link className="inline-flex min-h-10 items-center rounded-xl border border-black/10 px-4 text-sm font-semibold" href="/api/admin/event-demo/export/tags">Export tag list</Link>{canManage ? <><Link className="inline-flex min-h-10 items-center rounded-xl border border-black/10 px-4 text-sm font-semibold" href="/api/admin/event-demo/export/leads">Export leads</Link><Button loading={pending} onClick={() => start(async () => { const result = await cleanupExpiredEventDemoSessions(25); setCleanupMessage(result.message); })} leftIcon={<RefreshCw />}>Clean expired sessions</Button></> : null}</div></div>{cleanupMessage ? <p aria-live="polite" className="mt-4 rounded-xl bg-neutral-100 px-4 py-3 text-sm">{cleanupMessage}</p> : null}</section>
    <CreateTagForms canManage={canManage} />
    <EventDemoFilters query={query} />
    <section className="grid gap-3 rounded-2xl border border-black/[.07] bg-white p-3 sm:grid-cols-3"><Pager name="tags" query={query} page={tags.page} totalPages={tags.totalPages} total={tags.total} /><Pager name="sessions" query={query} page={sessions.page} totalPages={sessions.totalPages} total={sessions.total} /><Pager name="leads" query={query} page={leads.page} totalPages={leads.totalPages} total={leads.total} /></section>
    <LeadSearch />
    <section><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-neutral-500">Live overview</p><h2 className="mt-1 text-2xl font-semibold tracking-[-.04em]">Fair metrics</h2></div><p className="text-sm text-neutral-600">Completion rate <strong className="text-neutral-950">{completion}%</strong></p></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Started today", metrics.sessionsStartedToday], ["Completed today", metrics.profilesCompletedToday], ["Profile views today", metrics.profilesViewedToday], ["Marketing consents today", metrics.leadsConsentedToday]].map(([label, value]) => <article key={String(label)} className="rounded-2xl border border-black/[.07] bg-white p-4"><p className="text-sm text-neutral-600">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></article>)}</div></section>
    <section className="overflow-hidden rounded-3xl border border-black/[.07] bg-white"><div className="flex items-center justify-between border-b border-black/[.07] px-5 py-4"><div><h2 className="font-semibold">Demo tags</h2><p className="text-sm text-neutral-600">{tags.total} tags · statuses and temporary data remain private.</p></div><Tag className="size-5 text-neutral-500" aria-hidden="true" /></div><div className="overflow-x-auto"><table className="min-w-[1050px] w-full text-left text-sm"><thead className="border-b border-black/[.07] text-xs uppercase tracking-wide text-neutral-500"><tr><th className="p-4">Tag</th><th>Public code</th><th>Status</th><th>Use</th><th>Latest session</th><th className="p-4">Actions</th></tr></thead><tbody>{tags.rows.map((tag) => <tr key={tag.id} className="border-b border-black/[.06] align-top last:border-0"><td className="p-4"><p className="font-semibold">{tag.internalName}</p><p className="text-xs text-neutral-500">{tag.sessionDurationMinutes} min · {tag.isEnabled ? "Enabled" : "Disabled"}</p></td><td><code className="text-xs">{tag.publicCode}</code></td><td><span className="inline-flex rounded-full bg-neutral-100 px-2 py-1 text-xs font-medium">{badge(tag.status)}</span></td><td>{tag.usageCount} scans<br /><span className="text-xs text-neutral-500">{date(tag.lastUsedAt)}</span></td><td>{tag.latestSession ? <><span>{badge(tag.latestSession.status)}</span><p className="mt-1 text-xs text-neutral-500">Expires {date(tag.latestSession.expiresAt)}</p>{tag.latestSession.cleanupRequired ? <p className="mt-1 flex items-center gap-1 text-xs font-medium text-amber-800"><ShieldAlert className="size-3" />Cleanup required</p> : null}</> : "—"}</td><td className="p-4"><TagActions tag={tag} canManage={canManage} /></td></tr>)}{!tags.rows.length ? <tr><td className="p-10 text-center text-neutral-600" colSpan={6}>No demo tags created yet.</td></tr> : null}</tbody></table></div></section>
    <section className="grid gap-6 xl:grid-cols-2"><div className="overflow-hidden rounded-3xl border border-black/[.07] bg-white"><div className="border-b border-black/[.07] px-5 py-4"><h2 className="font-semibold">Recent sessions</h2><p className="text-sm text-neutral-600">{sessions.total} total · no pet or owner details shown.</p></div><ul>{sessions.rows.slice(0, 10).map((session) => <li key={session.id} className="flex items-center justify-between gap-3 border-b border-black/[.06] px-5 py-4 last:border-0"><div><p className="font-medium">{session.publicRef}</p><p className="mt-1 text-xs text-neutral-500">{date(session.createdAt)} · photo {session.hasPhoto ? "yes" : "no"} · marketing {session.marketingConsent ? "yes" : "no"}</p></div><span className="rounded-full bg-neutral-100 px-2 py-1 text-xs font-medium">{badge(session.status)}</span></li>)}{!sessions.rows.length ? <li className="p-10 text-center text-sm text-neutral-600">No sessions yet.</li> : null}</ul></div><div className="overflow-hidden rounded-3xl border border-black/[.07] bg-white"><div className="border-b border-black/[.07] px-5 py-4"><h2 className="font-semibold">Event leads</h2><p className="text-sm text-neutral-600">Only contacts that explicitly opted in are shown.</p></div><ul>{leads.rows.slice(0, 10).map((lead) => <li key={`${lead.email}-${lead.createdAt}`} className="flex items-center justify-between gap-3 border-b border-black/[.06] px-5 py-4 last:border-0"><div><p className="font-medium">{lead.firstName ?? "Launch contact"}</p><p className="mt-1 text-xs text-neutral-500">{lead.email} · {lead.source}</p></div><CheckCircle2 className="size-4 text-emerald-700" aria-label="Marketing consent recorded" /></li>)}{!leads.rows.length ? <li className="p-10 text-center text-sm text-neutral-600">No marketing-consented leads yet.</li> : null}</ul></div></section>
  </div>;
}
